const AstAppConfig = {
    alwaysSaveSearchState: false,
    backupsLocation: "",
    previewLocation: "",
    licenseAccepted: false,
    openDevToolsInMain: false,
    openDevToolsInPreview: false,
    resizeEngine: "sharp",
    sitesLocation: "",
    startScreen: "",
    timeFormat: 12,
    closeEditorOnSave: true,
    wideScrollbars: false,
    showModificationDate: true,
    showModificationDateAsColumn: false,
    showPostSlugs: false,
    showPostTags: true,
    postsOrdering: 'id DESC',
    pagesOrdering: ' DESC',
    tagsOrdering: 'id DESC',
    authorsOrdering: 'id DESC',
    appTheme: 'system',
    language: 'en-gb',
    languageType: 'default',
    enableAdvancedPreview: false,
    editorFontSize: 18,
    editorFontFamily: 'sans-serif',
    experimentalFeatureAppAutoBeautifySourceCode: false,
    experimentalFeatureAppFtpAlt: false,
    uiZoomLevel: 1.0
};

module.exports = AstAppConfig;
