export default {
    author: {
        addNewAuthor: 'Add new author',
        authorDataParsingErrorMessage: 'An error occurred during parsing author data for ID: ',
        authorHasBeenUpdated: 'Author has been updated',
        authorLink: 'Author link',
        authorNameCannotBeEmptyErrorMessage: 'Author name cannot be empty. Please try other name.',
        authorNameInUseErrorMessage: 'Provided author name is in use. Please try other author name.',
        authorNameSimilarInUseErrorMessage: 'Provided author name in a similar form (case insensitive) is in use. Please try other author name.',
        authorPage: 'Author page',
        authorSlugCannotBeEmpty: 'Author slug cannot be empty',
        avatar: 'Avatar',
        avatarAndFeaturedImage: 'Avatar and Featured image',
        cannotRemoveMainAuthor: 'You cannot remove the main author.',
        editAuthor: 'Edit author',
        eMail: 'E-mail',
        filterOrSearchAuthors: 'Filter or search authors...',
        gravatarEmailWarningMessage: 'Enter the email address you used for registering your account on Gravatar.',
        mainAuthor: 'Main author',
        mainAuthorCannotBeRemoved: 'This is a main author of this website. It cannot be removed.',
        newAuthorHasBeenCreated: 'New author has been created',
        noAuthorsMatchingYourCriteria: 'There are no authors matching your criteria.',
        removeAuthorsMessage: 'Do you really want to remove selected authors?',
        removeAuthorsSuccessMessage: 'Selected authors have been removed',
        saveAndPreviewNotAvailableDueToNoSupportForAuthorPagesInTheme: 'The "Save &amp; Preview" option is not available due to lack of support for author pages in your theme.',
        selectAuthorPage: 'Select author page',
        themeDoesNotSupportFeaturedImagesForAuthors: 'Your theme does not support featured images for authors',
        toUseThisOptionEnableIndexingAuthorPages: 'To use this option, first enable indexing of author pages in SEO settings.',
        useGravatarMessage: 'Use <a href="https://gravatar.com/" target="_blank" rel="noopener noreferrer">Gravatar </a> to provide your author avatar',
        useGravatarServiceMessage: 'In order to use Gravatar service provide the author e-mail at first.',
        website: 'Website'
    },
    menu: {
        addMenuItem: 'Add menu item',
        addNewMenu: 'Add new menu',
        addNewMenuItem: 'Add new menu item',
        addSubmenu: 'Add submenu',
        addSubmenuItem: 'Add submenu item',
        assignedMenu: 'Assigned menu',
        classCSS: 'CSS class',
        createNewMenu: 'Create new menu',
        deleteThisMenuItem: 'Delete this menu item',
        editMenuItem: 'Edit menu item',
        editMenuName: 'Edit menu name',
        editThisMenuItem: 'Edit this menu item',
        externalLink: 'External link',
        externalURL: 'External URL',
        hideThisMenuItem: 'Hide this menu item',
        internalLink: 'Internal link',
        items: 'Items',
        label: 'Label',
        likedItemError: 'Linked item is not rendered (empty tag/author page), not exists or is trashed',
        likedItemIsADraft: 'Linked item is a draft',
        linkRelAttribute: 'Link rel attribute',
        linkTitleAttribute: 'Link Title attribute',
        menu: 'Menu',
        menuIemsRemoveMessage: 'Do you really want to remove selected menu item?',
        menuItemIsHidden: 'This menu item is hidden',
        menuNameCannotBeEmptyCreateNewMenuErrorMessage: 'The menu name field must be non-empty. Please create a new menu again.',
        menuNameCannotBeEmptyErrorMessage: 'The field menu name should not be left empty. Please edit a menu name again.',
        menuNameExistsErrorMessage: 'The menu name supplied already exists. Please use a different name.',
        menuNameHasBeenEdited: 'Menu name has been edited',
        menuNameInUseErrorMessage: 'The menu name is in use. Please try to change a menu name again.',
        menusRemoveMessage: 'Do you really want to remove selected menus?',
        menusRemoveSuccessMessage: 'Selected menus have been removed',
        newMenuCreated: 'New menu has been created',
        noMenusAvailable: 'No menus available',
        noMenusCreateNewOne: 'You don\'t have any menu, yet. Let\'s create the first one!',
        noMenusMessage: 'There are no menu items; create new ones via the "Add menu item" button above.',
        provideNameForNewMenu: 'Provide a name for your new menu:',
        provideNewNameForMenu: 'Provide a new name for the selected menu:',
        selectItemType: 'Select item type',
        selectLinkTarget: 'Select link target',
        showThisMenuItem: 'Show this menu item',
        textSeparator: 'Text separator',
        type: 'Type',
        unassigned: "Unassigned"
    },
    post: {
        addNewPost: 'Add new post',
        all: 'All',
        author: 'Author',
        drafts: 'Drafts',
        duplicate: 'Duplicate',
        duplicatePostErrorMessage: 'An error occured during duplicating of selected posts. Please try again.',
        duplicatePostSuccessMessage: 'Selected posts have been duplicated',
        editorBlock: 'Block editor',
        editorBlockInfo: 'A modern and intuitive editor with shortkey and markdown support to make blogging easy, with no need to worry about HTML or other code elements.',
        editorBlockNotSupportedEditPostInfo: 'The current theme does not support the block editor used in this post. This post can be not properly rendered on the output files.',
        editorBlockNotSupportedNewPostInfo: 'The current theme does not support the block editor you want to use. This post can be not properly rendered on the output files.',
        editorBlockUse: 'Use Block editor',
        editorMarkdown: 'Markdown editor',
        editorMarkdownInfo: 'This editor supports Markdown syntax as shorthand for producing content quickly; great for extensive, no-frills projects such as documentation.',
        editorMarkdownUse: 'Use Markdown editor',
        editorWYSIWYG: 'WYSIWYG editor',
        editorWYSIWYGInfo: 'This editor provides a familiar word-processing experience, with additional tools for users that want to control every aspect of their page content.',
        editorWYSIWYGUse: 'Use WYSIWYG editor',
        editPostAnyway: 'Edit post anyway',
        excluded: 'Excluded',
        excludeFromHomepage: 'Exclude from homepage',
        featured: 'Featured',
        filterOrSearchPosts: 'Filter or search posts...',
        hidden: 'Hidden',
        hidePost: 'Hide Post',
        includeInHomepage: 'Include in homepage',
        markAsDraft: 'Mark as draft',
        markAsFeatured: 'Mark as featured',
        markAsUnfeatured: 'Mark as unfeatured',
        modificationDate: 'Modification date',
        moveToTrash: 'Move to trash',
        noPostsMatchingYourCriteria: 'There are no posts matching your criteria.',
        openEditorAnyway: 'Open editor anyway',
        postLink: 'Post link',
        postPage: 'Post page',
        postStatusChangeSuccessMessage: 'Status of the selected posts has been changed',
        publicationDate: 'Publication date',
        publish: 'Publish',
        published: 'Published',
        removePostMessage: 'Do you really want to remove selected posts? It cannot be undone.',
        removePostSuccessMessage: 'Selected posts have been removed',
        selectPostPage: 'Select post page',
        thisPostIsADraft: 'This post is a draft',
        thisPostIsExcludedFromHomepage: 'This post is excluded from homepage',
        thisPostIsFeatured: 'This post is featured',
        thisPostIsHidden: 'This post is hidden',
        title: 'Title',
        trashed: 'Trashed',
        url: 'URL'
    },
    site: {
        createNewWebsite: 'Create new website',
        createWebsite: 'Create website',
        createYourFirstWebsite: 'Create your first website',
        creationInProgress: 'Creation in progress...',
        erroOcurredDuringSiteDatabaseCreationInfo: 'An error occurred during site database creation. Please check your antivirus software and try again. You can also need to remove the invalid website catalog from Publii sites directory.',
        siteWithThisNameExists: 'Site using this name exists!',
        websiteAuthor: 'Author name',
        websiteAuthorRequired: 'author name is required and should contains letters',
        websiteName: 'Website name',
        websiteNameRequired: 'website name is required',
        siteName: 'Site name:',
    },
    sync: {
        configureServer: 'Configure Server',
        goToAppSettings: 'Go to app settings',
        goToSettings: 'Go to settings',
        lastRendered: 'Last rendered',
        lastSync: 'Last sync',
        preparationError: 'Preparation error',
        preparedToUpload: 'Prepared to upload',
        preparingFiles: 'Preparing files',
        previewCatalogDoesNotExistInfo: 'The preview catalog does not exist. Please go to the App Settings and select the correct preview directory first.',
        previewChanges: 'Preview your changes',
        provideAccessData: 'Provide access data',
        siteIsInSync: 'Site is in sync',
        syncInProgress: 'Sync in progress',
        syncYourWebsite: 'Sync your website',
        youHaventSelectedAnyThemeInfo: 'You haven\'t selected any theme. Please go to the Settings and select the theme first.',
        syncInProgressMessage: 'During sync process you cannot change site name.',
    },
    tag: {
        addNewTag: 'Add new tag',
        createFirstTag: 'You don\'t have any tag, yet. Let\'s create the first one!',
        editTag: 'Edit tag',
        filterOrSearchTags: 'Filter or search tags...',
        hideTag: 'Hide tag',
        leaveBlankToUseDefaultTagPageURL: 'Leave blank to use a default tag page URL',
        newTagHasBeenCreated: 'New tag has been created',
        noSupportFoFeaturedImagesForTags: 'Your theme does not support featured images for tags.',
        noTagsAvailable: 'No tags available',
        noTagsMatchingYourCriteria: 'There are no tags matching your criteria.',
        removeTagMessage: 'Do you really want to remove selected tags?',
        removeTagSuccessMessage: 'Selected tags have been removed',
        saveAndPreviewNotAvailableDueToNoSupportForTagPagesInTheme: 'The "Save &amp; Preview" option is not available due to lack of support for tag pages in your theme.',
        selectTagPage: 'Select tag page',
        tagDataParsingErrorMessage: 'An error occurred during parsing tag data for ID: ',
        tagHasBeenEdited: 'Tag has been edited',
        tagLink: 'Tag link',
        tagNameCannotBeEmptyErrorMessage: 'Tag name cannot be empty. Please try other name.',
        tagNameInUseErrorMessage: 'Provided tag name is in use. Please try other tag name.',
        tagNameNotAllowedErrorMessage: 'Selected tag name/slug is not allowed.',
        tagNameSimilarInUseErrorMessage: 'Provided tag name in a similar form (case insensitive) is in use. Please try other tag name.',
        tagPage: 'Tag page',
        tagsListLink: 'Tags list link',
        tagStatusChangeSuccessMessage: 'Status of the selected tags has been changed',
        tagWillNotAppearInGgeneratedTagLists: 'Tag will not appear in any generated tag list such as post or tag/s pages.',
        thisTagIsHidden: 'This tag is hidden',
        toUseThisOptionEnableIndexingTagPages: 'To use this option, first enable indexing of tag pages in SEO settings.'
    },
    theme: {
        addThemeSuccessMessage: 'Theme has been successfully added.',
        authorsPostsPerPage: 'Authors posts per page:',
        authorsPostsPerPageInfo: 'Use -1 as value if you need to display all authors posts on page.',
        changeAppTheme: 'Change application theme',
        customSettings: 'Custom settings',
        defaultPostTemplate: 'Default post template',
        defaultTemplate: 'Default template',
        deleteTheme: 'Delete theme',
        dropYourThemeHere: 'Drop your theme here',
        excerptLength: 'Excerpt length:',
        getMoreThemes: 'Get more themes',
        goToThemesManager: 'Go to the themes manager',
        installTheme: 'Install theme',
        leaveBlankToUseDefault: 'Leave it blank to use default value',
        postOptions: 'Post options',
        postOptionsInfo: 'The Post options section allows you to set global options for what extra information should be included in your posts. Changes made in this section will affect all posts on your site, but you can also override the App Settings on the Post Edit screen for each individual post if necessary.',
        postsPerPage: 'Posts per page:',
        postsPerPageInfo: 'Use -1 as value if you need to display all posts on page.',
        removeThemeMessagePT1: 'Do you really want to remove the ',
        removeThemeMessagePT2: ' theme?',
        removeThemeSuccessMessage: 'Theme has been successfully removed.',
        resetThemeSettings: 'Reset theme settings',
        saveSettingsSuccessMessage: 'Theme settings has been successfully saved.',
        settingsResetMessage: 'Do you really want to reset the theme settings?',
        settingsResetSuccessMessage: 'Theme settings has been reset.',
        tagsPostsPerPage: 'Tags posts per page:',
        tagsPostsPerPageInfo: 'Use -1 as value if you need to display all tag posts on page.',
        themes: 'Themes',
        themeSettings: 'Theme Settings',
        translations: 'Translations',
        translationsInfo: 'If you need to translate theme phrases to languages other than english - please check our documentation regarding <a href="https://getpublii.com/dev/translations-api/" target="_blank" rel="noopener noreferrer">Translations API</a><br><br>',
        updateThemeSuccessMessage: 'Theme has been successfully updated.',
        uploadThemeErrorMessage: 'The uploaded files are incorrect. Please upload theme directory or theme ZIP file.',
        websiteLogo: 'Website logo:'
    },
    ui: {
        aboutPublii: 'About Publii',
        alternativeText: 'Alternative text',
        appConfiguration: 'Application configuration',
        appSettings: 'App settings',
        authors: 'Authors',
        basicInformation: 'Basic information',
        basicSettings: 'Basic settings',
        cancel: 'Cancel',
        canonicalURL: 'Canonical URL',
        caption: 'Caption',
        checkDocumentation: 'Check Publii documentation',
        credits: 'Credits',
        customTemplate: 'Custom template',
        delete: 'Delete',
        description: 'Description',
        donate: 'Donate',
        edit: 'Edit',
        featuredImage: 'Featured image',
        frontpageLink: 'Frontpage link',
        githubRepository: 'Github repository',
        goBack: 'Go back',
        help: 'Help',
        hide: 'Hide',
        id: 'ID',
        ifCanonicalURLIsSetMmetaRobotsTagiInored: 'If canonical URL is set, the meta robots tag is ignored.',
        indexFollow: 'index, follow',
        indexNofollow: 'index, nofollow',
        lastModified: 'Last modified',
        leaveBlankToUseDefaultPageTitle: 'Leave it blank to use a default page title',
        linkTarget: 'Link target',
        menus: 'Menus',
        metaDescription: 'Meta Description',
        metaRobotsIndex: 'Meta robots index',
        more: 'More',
        moreInformationOnPublii: 'More informations about Publii',
        moreItems: 'More items',
        name: 'Name',
        newWindow: 'New window',
        noindexFollow: 'noindex, follow',
        noindexNofollow: 'noindex, nofollow',
        notAvailableInYourTheme: 'Not available in your theme',
        otherOptions: 'Other options',
        pageTitle: 'Page Title',
        pleaseFillAllRequiredFields: 'Please fill all required fields',
        posts: 'Posts',
        publiiOnGithub: 'View Publii on Github',
        renderFrontPageOnly: 'Render front page only',
        renderFullWebsite: 'Render full website',
        reportBugInSupportdesk: 'Report a bug in our supportdesk',
        reportIssue: 'Report an issue',
        restore: 'Restore',
        sameWindow: 'The same window',
        saveAndPreview: 'Save & Preview',
        saveAndPreview: 'Save &amp; Preview',
        saveChanges: 'Save Changes',
        saveSettings: 'Save Settings',
        seo: 'SEO',
        server: 'Server',
        show: 'Show',
        siteSettings: 'Site settings',
        slug: 'Slug',
        supportPublii: 'Support Publii and donate today!',
        tags: 'Tags',
        theme: 'Theme',
        tools: 'Tools',
        unhide: 'Unhide',
        useSiteGlobalSettings: 'Use site global settings',
        none: 'None',
        customLink: 'Custom link',
        AMP: 'AMP',
    },
    settings: {
        language: 'Language:',
        customLanguageCode: 'Custom language code:',
        enableSpellchecker: 'Enable spellchecker',
        currentTheme: 'Current theme:',
        noIndexWebsite: 'Noindex website',
        frontpage: 'Frontpage',
        pageTitle: 'Page Title:',
        metaDescription: 'Meta Description:',
        metaRobots: 'Meta Robots:',
        usePrettyURLs: 'Use pretty URLs',
        alwaysAddIndexHTMLInURLs: 'Always add index.html in URLs',
        tagPrefix: 'Tag prefix:',
        authorPrefix: 'Author prefix:',
        paginationPhrase: 'Pagination phrase:',
        errorPage: 'Error page:',
        searchPage: 'Search page:',
        createXMLSitemap: 'Create XML Sitemap',
        content: 'Content',
        excludedFiles: 'Excluded files',
        generateOpenGraphTags: 'Generate Open Graph tags',
        fallbackImage: 'Fallback image',
        useAsTitlePageTitle: 'Use as a title page title',
        facebookAppID: 'Facebook App ID',
        generateTwitterCards: 'Generate Twitter cards',
        twitterUsername: 'Twitter username',
        cardTypes: 'Card types:',
        enableAMP: 'Enable AMP',
        themePrimaryColor: 'Theme primary color',
        fallbackLogoImage: 'Fallback logo image',
        googleAnalyticsTrackingID: 'Google Analytics Tracking ID',
        enableSharingButtons: 'Enable sharing buttons',
        system: 'System',
        facebook: 'Facebook',
        twitter: 'Twitter',
        pinterest: 'Pinterest',
        linkedIn: 'LinkedIn',
        tumblr: 'Tumblr',
        whatsApp: 'WhatsApp',
        footerText: 'Footer text',
        addGDPRCookieBanner: 'Add GDPR Cookie banner',
        cookiePopup: 'Cookie Popup',
        gdprTitle: 'Title',
        linkLabel: 'Link label',
        privacyPolicyURL: 'Privacy policy URL',
        privacyPolicyPage: 'Privacy policy page',
        privacyPolicyPageURL: 'Privacy policy page URL',
        saveButtonLabel: 'Save button label',
        openPopupWindowBy: 'Open Popup window by',
        badgeLabel: 'Badge label',
        anchorLink: 'Anchor link',
        cookieGroups: 'Cookie Groups',
        enableHTMLCompression: 'Enable HTML compression',
        enableCSSCompression: 'Enable CSS compression',
        removeHTMLComments: 'Remove HTML comments',
        enableMediaLazyLoad: 'Enable media lazy load',
        enableResponsiveImages: 'Enable responsive images',
        versionParameter: 'Version parameter',
        responsiveImagesQuality: 'Responsive Images quality',
        enableRSSFeed: 'Enable RSS feed',
        enableJSONFeed: 'Enable JSON feed',
        feedTitle: 'Feed title:',
        customFeedTitle: 'Custom feed title',
        pageName: 'Page name',
        showFullText: 'Show full text',
        showOnlyFeaturedPosts: 'Show only featured posts',
        excludeFeaturedPosts: 'Exclude featured posts',
        numberOfPostsInFeed: 'Number of posts in feed',
        showFeaturedImage: 'Show Featured image',
        postsOrderBy: 'Posts order by:',
        postsOrdering: 'Posts ordering:',
        featuredPostsOrderBy: 'Featured posts order by:',
        featuredPostsOrdering: 'Featured posts ordering:',
        hiddenPostsOrderBy: 'Hidden posts order by:',
        hiddenPostsOrdering: 'Hidden posts ordering:',
        relatedPostsSelectionMechanism: 'Related posts selection mechanism:',
        relatedPostsOrdering: 'Related posts ordering:',
        relatedPostsOptions: 'Related posts options',
        codeEditor: 'Code editor (CodeMirror)',
        indentSize: 'Indent size (spaces)',
        enableAutoIndent: 'Enable auto-indent',
        advancedOptions: 'Advanced options',
        spellcheckerDoesNotSupportLanguage: 'The spellchecker does not support your selected website language. We recommend to disable this feature.',
        notSelected: 'Not selected',
        themeDoesNotHaveSupportedFeaturesList: '<p>Your theme <strong>config.json</strong> file does not contain <strong>supportedFeatures</strong> section. Please update or modify your theme to get accurate message about features which are not supported by your currently used theme. <a href="https://getpublii.com/dev/theme-supported-features" target="_blank" rel="noopener noreferrer">Read more about supported features</a>.</p>',
        dontIndexThisPage: 'Ask the search engine not to crawl the whole website.',
        disableHomepagePaginationIndexing: 'Disable homepage pagination indexing',
        homepageNoIndexPagination: 'If this option is enabled your homepage pagination files will be excluded from the sitemap and will get <strong>noindex, follow</strong> robots metatag.',
        postPageTitleVariables: 'The following variables can be used in the Post Page Title: %posttitle, %sitename, %authorname',
        hideCustomExcerptsOnPostPages: 'Hide custom excerpts on post pages',
        hideCustomExcerptsOnPostPagesInfo: 'If this option is enabled your post pages won\'t display text which is placed above \"Read more\" element in the post editor.',
        tagsListPage: 'Tags list page',
        themeDoesNotSupportTagsListPage: 'Your theme does not support Tags list page.',
        tagsListPageTitleVariables: 'The following variables can be used in the Tags List Page Title: %sitename',
        tagPageTitleVariables: 'The following variables can be used in the Tag Page Title: %tagname, %sitename',
        displayEmptyTags: 'Display tags w/o posts',
        displayEmptyTagsInfo: 'If this option is enabled tags without posts assigned to them will still have their subpages created and appear on the tags list.',
        disableTagsPaginationIndexing: 'Disable tags pagination indexing',
        disableTagsPaginationIndexingInfo: 'If this option is enabled your tags pagination files will be excluded from the sitemap and will get <strong>noindex, follow</strong> robots metatag.',
        disableTagsPagination: 'Disable tags pagination',
        disableTagsPaginationInfo: 'If this option is enabled your tags pagination won\'t be generated.',
        authorPage: 'Author page',
        authorPageTitleVariables: 'The following variables can be used in the Author Page Title: %authorname, %sitename',
        displayEmptyAuthors: 'Display authors w/o posts',
        displayEmptyAuthorsInfo: 'If this option is enabled authors without posts assigned to them will still have their subpages created and appear on the authors list.',
        disableAuthorsPaginationIndexing: 'Disable authors pagination indexing',
        disableAuthorsPaginationIndexingInfo: 'If this option is enabled your authors pagination files will be excluded from the sitemap and will get <strong>noindex, follow</strong> robots metatag.',
        disableAuthorsPagination: 'Disable authors pagination',
        disableAuthorsPaginationInfo: 'If this option is enabled your authors pagination won\'t be generated.',
        themeDoesNotSupport404ErrorPage: 'Your theme does not support 404 Error page.',
        errorPageTitleVariables: 'The following variables can be used in the Error Page Title: %sitename',
        themeDoesNotSupportSearchPage: 'Your theme does not support Search page.',
        searchPageTitleVariables: 'The following variables can be used in the Search Page Title: %sitename',
        usePrettyURLsInfo: 'If this option is enabled your post URLs won\'t contain the .html suffix e.g. it will change URLs from <strong>https://example.com/post.html</strong> to <strong>https://example.com/post/</strong>.',
        cannotAddIndexHTMLInURLsInfo: 'Enable this option if you cannot enable loading index.html files by default when catalog on your server is opened.',
        tagPrefixInfo: 'Prefixes entered here will be added before the tag slug in the URL e.g. <strong>https://example.com/TAG_PREFIX/tag-slug</strong>.<br>This prefix is also used to generate tags list page (if supported in your theme) as <strong>https://example.com/TAG_PREFIX/index.html</strong>',
        authorPrefixInfo: 'Defines the prefix that appears before the author slug in a URL e.g. <strong>https://example.com/AUTHOR_PREFIX/author-slug</strong><br>',
        paginationPhraseInfo: 'Defines the phrase used before the page number in a URL e.g. <strong>https://example.com/tags/tag-slug/page/2</strong>.<br>',
        themeDoesNotSupportErrorPages: 'Your theme does not support error pages',
        themeDoesNotSupportSearchPages: 'Your theme does not support search pages',
        toViewSitemapEnableIndexingInfo: 'To view sitemap settings please disable the \'Ask search engines to not index this website\' option in the SEO Settings tab; the sitemap won\'t be generated for your website otherwise.',
        sitemapLinkInfo: 'You can find the XML sitemap here: <a :href="sitemapLink" class="sitemap-external-link" target="_blank" rel="noopener noreferrer">sitemap.xml</a>',
        tagPages: 'Tag pages',
        authorPages: 'Author pages',
        homepagePagination: 'Homepage pagination',
        externalImages: 'External images',
        excludeFilesFromSitemapInfo: 'Type a comma-separated list of HTML files or catalogs to exclude from the sitemap.<br>For example: <strong>avoid-this-file.html,avoid-this-catalog-too</strong>',
        useAsTitlePageTitleInfo: 'When this option is enabled, og:title and twitter:title metatags will contain the page title instead of the post title, tag name or author name.',
        facebookAppIDInfo: 'Read how to obtain <a href="https://developers.facebook.com/docs/apps/" target="_blank" rel="noopener noreferrer">Facebook App ID</a>',
        enableAMPInfo: 'AMP (accelerated mobile pages) creates mobile-optimized pages for your static content that render fast. <br/><strong>Please note:</strong>  when this option is enabled your website will load third-party scripts provided by Google\'s AMP CDN.',
        fallbackLogoImageInfo: 'The logo must fit in a 60 &times; 600 pixel box.',
        provideFacebookAppID: 'Please provide <a href="https://developers.facebook.com/docs/apps/" target="_blank" rel="noopener noreferrer">Facebook App ID</a>',
        howToPrepareYourThemeForGDPRInfo: 'Enabling the GDPR Cookie Popup requires some additional changes in your theme, especially if you are using third-party scripts. <a href="https://getpublii.com/dev/prepare-theme-gdpr-compliant/" target="_blank" rel="noopener noreferrer">Read how to prepare your theme for GDPR</a>',
        internalPage: 'Internal page',
        externalPage:'External page',
        selectPage: 'Select page',
        badgeAndCustomLink: 'Badge + custom link',
        badge: 'Badge',
        gdprBehaviourInfo: 'Remember to place a link with the above anchor in your website navigation or the website content (e.g. &lt;a href="#cookie-settings"&gt;Cookie preferences&lt;/a&gt;). Otherwise, your website\'s users might not be able to change their individual cookie preferences.',
        enableMediaLazyLoadInfo: 'Enable this option if you want to use native lazy loading that lazy loads images, videos and iframes.',
        enableResponsiveImagesInfo: 'Enable this option if you want to deliver different sized images at different screen resolutions depending on breakpoints defined through config.json file in a theme\'s folder.',
        versionParameterInfo: 'Add version parameter in CSS/JS URLs to skip browser cache. This option can cause that more files than usual will be required to sync during deployment',
        showFullTextInFeedInfo: 'Display full text of the post in the feed',
        showFeaturedImageInfo: 'Display a post\'s featured image in the feed',
        relatedPostsOptionsInfo: 'When enabled, related posts will be taken from all tags. When disabled, related posts will only be generated from the same tags as the current post.',
        editorWYSIWYGInfo: 'If the WYSIWYG editor strips out some tags from your HTML code, here you can add additional allowed elements.<br> For example: <strong>v-select[*],v-dropdown[*]</strong> will allow custom v-select and v-dropdown tags with any attributes.',
        postCreationDate: 'Post creation date',
        postTile: 'Post title',
        postModificationDate: 'Post modification date',
        postID: 'Post ID',
        descending: 'Descending',
        ascending: 'Ascending',
        byIDDescending: 'By ID descending',
        byIDAscending: 'By ID ascending',
        random: 'Random',
        useOnlyTitles: 'Use only titles',
        useOnlyTags: 'Use only tags',
        useTitlesAndTags: 'Use titles and tags',
        urls: 'URLs',
        sitemap: 'Sitemap',
        openGraph: 'Open Graph',
        twitterCards: 'Twitter Cards',
        GDPR: 'GDPR',
        websiteSpeed: 'Website Speed',
        RSSJSONFeed: 'RSS/JSON Feed',
        postsListing: 'Posts Listing',
        editors: 'Editors',
        twitteSummaryCard: 'Summary card',
        twitteSummaryCardLargeImage: 'Summary card with large image',
    },
};
