export default {
    author: {
        addNewAuthor: 'Add new author',
        authorDataParsingErrorMessage: 'An error occurred during parsing author data for ID: ',
        authorHasBeenUpdated: 'Author has been updated',
        authorLink: 'Author link',
        authorName: 'Author name',
        authorNameCannotBeEmptyErrorMessage: 'Author name cannot be empty. Please try other name.',
        authorNameInUseErrorMessage: 'Provided author name is in use. Please try other author name.',
        authorNameSimilarInUseErrorMessage: 'Provided author name in a similar form (case insensitive) is in use. Please try other author name.',
        authorPage: 'Author page',
        authorSlugCannotBeEmpty: 'Author slug cannot be empty',
        avatar: 'Avatar',
        avatarAndFeaturedImage: 'Avatar and Featured image',
        cannotRemoveMainAuthor: 'You cannot remove the main author.',
        changePostAuthor: 'Change post author',
        editAuthor: 'Edit author',
        eMail: 'E-mail',
        filterOrSearchAuthors: 'Filter or search authors...',
        gravatarEmailWarningMessage: 'Enter the email address you used for registering your account on Gravatar.',
        mainAuthor: 'Main author',
        mainAuthorCannotBeRemoved: 'This is a main author of this website. It cannot be removed.',
        newAuthorHasBeenCreated: 'New author has been created',
        noAuthorsMatchingYourCriteria: 'There are no authors matching your criteria.',
        removeAuthorsMessage: 'Do you really want to remove selected authors?',
        removeAuthorsSuccessMessage: 'Selected authors have been removed',
        saveAndPreviewNotAvailableDueToNoSupportForAuthorPagesInTheme: 'The "Save &amp; Preview" option is not available due to lack of support for author pages in your theme.',
        selectAuthor: 'Select author',
        selectAuthorPage: 'Select author page',
        themeDoesNotSupportFeaturedImagesForAuthors: 'Your theme does not support featured images for authors',
        toUseThisOptionEnableIndexingAuthorPages: 'To use this option, first enable indexing of author pages in SEO settings.',
        useGravatarMessage: 'Use <a href="https://gravatar.com/" target="_blank" rel="noopener noreferrer">Gravatar </a> to provide your author avatar',
        useGravatarServiceMessage: 'In order to use Gravatar service provide the author e-mail at first.',
        website: 'Website'
    },
    date: {
        apr: 'Apr',
        aug: 'Aug',
        changePostPublicationDate: 'Change post publication date',
        dec: 'Dec',
        feb: 'Feb',
        jan: 'Jan',
        jul: 'Jul',
        jun: 'Jun',
        mar: 'Mar',
        may: 'May',
        nov: 'Nov',
        oct: 'Oct',
        sep: 'Sep'
    },
    editor: {
        blockEditorHelpPanelDesc: 'You can insert a block either by clicking the                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>+</span>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                or <span>TAB</span> button on a new line, or typing the following shortcuts or markdown syntax on a new line:',
        dragAndDropImgToEditor: 'Drag and drop an image onto the editor',
        element: 'Element',
        markdown: 'Markdown',
        markdownHelpPanelDesc: 'You can easly manage headings, text styles or create other HTML elements by using the following keyboard shortcuts or typing markdown syntax:',
        shortcuts: 'Shortcuts'
    },
    file: {
        backups: 'Backups',
        createBackup: 'Create backup',
        createBackupConfirmMsg: 'Select a name for your backup - filename can contain only alphanumeric characters, dashes and underscores:',
        createBackupErrorMsg: 'An error occurred during backup creation. Please try again.',
        createBackupNameEmptyMsg: 'Provided filename cannot be empty. Please try again with a different name.',
        createBackupNameInUseMsgPt1: 'Provided filename',
        createBackupNameInUseMsgPt2: 'is used by an existing backup. Please try again with a different name.',
        createBackupSuccessMsg: 'Backup has been created.',
        createFirstBackupMsg: 'You don\'t have any backups, yet. Let\'s create the first one!',
        creatingBackup: 'Creating backup',
        creationDate: 'Creation date',
        deletBackupsConfirmMsg: 'Do you really want to remove the selected backups? This action cannot be undone.',
        deletBackupsErrorMsg: 'An error occurred during selected backup file removal. Please try again.',
        deletBackupsSuccessMsg: 'Selected backups have been removed',
        filename: 'Filename',
        fileSize: 'File Size',
        noBackupsAvailable: 'No backups available',
        operations: 'Operations',
        rename: 'Rename',
        renameBackupConfrimLabel: 'Rename file',
        renameBackupConfrimMsg: 'Please specify a new backup filename:',
        renameBackupErrorMsg: 'An error occurred while renaming the selected backup file. Please try again.',
        renameBackupNameEmptyMsg: 'The backup filename cannot be empty. Please try again.',
        renameBackupNameInUseMsg: 'The specified name is used by other backup file. Please try again.',
        renameBackupSameNameMsg: 'The specified name is the same as the old name. Please try again.',
        renameBackupSuccessMsg: 'The backup has been sucessfully renamed.',
        restore: 'Restore',
        restoreBackupConfrimLabel: 'Restore backup',
        restoreBackupConfrimMsg: 'Do you really want to restore the selected backup? Existing files will be overwritten.',
        restoreBackupErrorMsg: 'An error occurred while restoring the selected backup file: ',
        restoreBackupSuccessMsg: 'The website has been successfully restored.'
    },
    gdpr: {
        addGroup: 'Add group',
        groupID: 'Group ID',
        groupName: 'Group name',
        state: 'State'
    },
    image: {
        addImages: 'Add images',
        align: 'Align',
        centered: 'Centered',
        dropFeaturedImageOr: 'Drop featured image here or',
        dropToUploadPhotoOr: 'Drop to upload your photo or',
        eightColumns: '8 columns',
        fiveColumns: '5 columns',
        fourColumns: '4 columns',
        fullWidth: 'Full-width',
        image: 'Image',
        imageAlternativeText: 'Image alternative text',
        imageCaption: 'Image caption',
        insertEditGallery: 'Insert/Edit Gallery',
        layout: 'Layout',
        loadingImage: 'Loading image...',
        of: 'of',
        oneColumn: '1 column',
        pictures: 'pictures',
        removeImage: 'Remove image',
        sevenColumns: '7 columns',
        sixColumns: '6 columns',
        threeColumns: '3 columns',
        twoColumns: '2 columns',
        uploading: 'Uploading',
        wide: 'Wide'
    },
    langs: {
        addLanguageSuccessMessage: 'Language has been added',
        deleteLanguage: 'Delete language',
        dropYourLanguageHere: 'Drop your file here',
        getMoreLanguages: 'Get more languages',
        goToLanguagesManager: 'Go to the languages manager',
        installLanguage: 'Install language',
        languages: 'Languages',
        removeLanguageMessagePT1: 'Do you really want to remove the ',
        removeLanguageMessagePT2: ' language?',
        removeLanguageSuccessMessage: 'The selected language has been removed',
        updatedLanguageSuccessMessage: 'Selected language has been updated',
        uploadLanguageErrorMessage: 'An error occurred during installation. Please try again.'
    },
    link: {
        downloadAttribute: 'Download attribute:',
        insertEditLink: 'Insert/Edit link',
        linkInvalidMsg: 'Sorry! This link seems to be invalid.',
        linkTitleAttribute: 'Link title attribute:',
        previewLinkInBrowser: 'Preview this link in browser',
        previewOnlyExternalLinksMsg: 'You can preview only external links in the post editor',
        relAttribute: 'Rel attribute:',
        selectLinkType: 'Select link type'
    },
    menu: {
        addMenuItem: 'Add menu item',
        addNewMenu: 'Add new menu',
        addNewMenuItem: 'Add new menu item',
        addSubmenu: 'Add submenu',
        addSubmenuItem: 'Add submenu item',
        assignedMenu: 'Assigned menu',
        classCSS: 'CSS class',
        createNewMenu: 'Create new menu',
        deleteThisMenuItem: 'Delete this menu item',
        editMenuItem: 'Edit menu item',
        editMenuName: 'Edit menu name',
        editThisMenuItem: 'Edit this menu item',
        externalLink: 'External link',
        externalURL: 'External URL',
        hideThisMenuItem: 'Hide this menu item',
        internalLink: 'Internal link',
        items: 'Items',
        label: 'Label',
        likedItemError: 'Linked item is not rendered (empty tag/author page), not exists or is trashed',
        likedItemIsADraft: 'Linked item is a draft',
        linkRelAttribute: 'Link rel attribute',
        linkTitleAttribute: 'Link Title attribute',
        menu: 'Menu',
        menuIemsRemoveMessage: 'Do you really want to remove selected menu item?',
        menuItemIsHidden: 'This menu item is hidden',
        menuNameCannotBeEmptyCreateNewMenuErrorMessage: 'The menu name field must be non-empty. Please create a new menu again.',
        menuNameCannotBeEmptyErrorMessage: 'The field menu name should not be left empty. Please edit a menu name again.',
        menuNameExistsErrorMessage: 'The menu name supplied already exists. Please use a different name.',
        menuNameHasBeenEdited: 'Menu name has been edited',
        menuNameInUseErrorMessage: 'The menu name is in use. Please try to change a menu name again.',
        menusRemoveMessage: 'Do you really want to remove selected menus?',
        menusRemoveSuccessMessage: 'Selected menus have been removed',
        newMenuCreated: 'New menu has been created',
        noMenusAvailable: 'No menus available',
        noMenusCreateNewOne: 'You don\'t have any menu, yet. Let\'s create the first one!',
        noMenusMessage: 'There are no menu items; create new ones via the "Add menu item" button above.',
        provideNameForNewMenu: 'Provide a name for your new menu:',
        provideNewNameForMenu: 'Provide a new name for the selected menu:',
        selectItemType: 'Select item type',
        selectLinkTarget: 'Select link target',
        showThisMenuItem: 'Show this menu item',
        textSeparator: 'Text separator',
        type: 'Type',
        unassigned: "Unassigned"
    },
    post: {
        addNewPost: 'Add new post',
        all: 'All',
        author: 'Author',
        backToPosts: 'Back to posts',
        changePostDate: 'Change post date',
        characters: 'Characters',
        configureThemeBeforeGenaratingPreview: 'You have to configure theme for this website before generating preview of this post.',
        currentDefaultTemplate: 'Current default template',
        drafts: 'Drafts',
        duplicate: 'Duplicate',
        duplicatePostErrorMessage: 'An error occured during duplicating of selected posts. Please try again.',
        duplicatePostSuccessMessage: 'Selected posts have been duplicated',
        editorBlock: 'Block editor',
        editorBlockInfo: 'A modern and intuitive editor with shortkey and markdown support to make blogging easy, with no need to worry about HTML or other code elements.',
        editorBlockNotSupportedEditPostInfo: 'The current theme does not support the block editor used in this post. This post can be not properly rendered on the output files.',
        editorBlockNotSupportedNewPostInfo: 'The current theme does not support the block editor you want to use. This post can be not properly rendered on the output files.',
        editorBlockUse: 'Use Block editor',
        editorMarkdown: 'Markdown editor',
        editorMarkdownInfo: 'This editor supports Markdown syntax as shorthand for producing content quickly; great for extensive, no-frills projects such as documentation.',
        editorMarkdownUse: 'Use Markdown editor',
        editorWYSIWYG: 'WYSIWYG editor',
        editorWYSIWYGInfo: 'This editor provides a familiar word-processing experience, with additional tools for users that want to control every aspect of their page content.',
        editorWYSIWYGUse: 'Use WYSIWYG editor',
        editPostAnyway: 'Edit post anyway',
        excluded: 'Excluded',
        excludeFromHomepage: 'Exclude from homepage',
        featured: 'Featured',
        filterOrSearchPosts: 'Filter or search posts...',
        hidden: 'Hidden',
        hidePost: 'Hide Post',
        includeInHomepage: 'Include in homepage',
        markAsDraft: 'Mark as draft',
        markAsFeatured: 'Mark as featured',
        markAsUnfeatured: 'Mark as unfeatured',
        min: 'min',
        modificationDate: 'Modification date',
        moveToTrash: 'Move to trash',
        noPostsMatchingYourCriteria: 'There are no posts matching your criteria.',
        openEditorAnyway: 'Open editor anyway',
        paragraphs: 'Paragraphs',
        postAuthor: 'Post author',
        postLink: 'Post link',
        postName: 'Post name:',
        postPage: 'Post page',
        postSettings: 'Post settings',
        postSlug: 'Post slug',
        postSlugLengthWarning: 'The post slug longer than 250 characters can lead to creation of broken files during the website rendering.',
        postSlugTooLong: 'Post slug is too long',
        postState: 'Post state',
        postStatusChangeSuccessMessage: 'Status of the selected posts has been changed',
        postTemplate: 'Post template',
        postWillNotAppearOnHomepageListMsg: 'Post will not appear on homepage listing',
        postWillNotAppearOnListMsg: 'Post will not appear in any generated post lists such as tag or author pages',
        publicationDate: 'Publication date',
        publish: 'Publish',
        published: 'Published',
        readingTime: 'Reading Time',
        removePostMessage: 'Do you really want to remove selected posts? It cannot be undone.',
        removePostSuccessMessage: 'Selected posts have been removed',
        selectPostPage: 'Select post page',
        sentences: 'Sentences',
        setCustomPostDate: 'Set custom post date',
        status: 'Status',
        thisPostIsADraft: 'This post is a draft',
        thisPostIsExcludedFromHomepage: 'This post is excluded from homepage',
        thisPostIsFeatured: 'This post is featured',
        thisPostIsHidden: 'This post is hidden',
        title: 'Title',
        trashed: 'Trashed',
        uniqueWords: 'Unique words',
        updatedOn: 'Updated on',
        url: 'URL',
        words: 'Words'
    },
    publii: {
        aboutPublii: 'About Publii',
        copyright: 'Copyright 2021 <a href="https://tidycustoms.net" target="_blank" rel="noopener noreferrer">TidyCustoms</a>. All rights reserved.<br>Publli is designed and maintained by core team with cooperation with <a href="https://github.com/dziudek" target="_blank" rel="noopener noreferrer">Dev Zen</a> and is made possible by the <a href="https://electronjs.org" target="_blank" rel="noopener noreferrer">Electron</a>Open Source project and other ',
        creditsIntro: 'Publii uses the following third-party Open Source Software:',
        dataCollectionInfo: '<strong>We do not collect any </strong>personal data while you use Publii app; also we do not store, we do not track, we do not allow third parties to collect personally identifiable information about you. ',
        homepage: 'Homepage',
        license: 'License',
        licensingInformation: 'Licensing information',
        openSourceSoftware: 'Open Source Software'
    },
    settings: {
        addGDPRCookieBanner: 'Add GDPR Cookie banner',
        advancedOptions: 'Advanced options',
        alwaysAddIndexHTMLInURLs: 'Always add index.html in URLs',
        alwaysSaveSearchState: 'Always save search state',
        anchorLink: 'Anchor link',
        appSettings: 'App settings',
        appSettingsSavedMsg: 'App settings has been successfully saved.',
        appSettingsSaveErrorMsg: 'An error occurred during saving the App Settings. Please try again.',
        ascending: 'Ascending',
        authorPage: 'Author page',
        authorPages: 'Author pages',
        authorPageTitleVariables: 'The following variables can be used in the Author Page Title: %authorname, %sitename',
        authorPrefix: 'Author prefix:',
        authorPrefixInfo: 'Defines the prefix that appears before the author slug in a URL e.g. <strong>https://example.com/AUTHOR_PREFIX/author-slug</strong><br>',
        authorsPrefixCannotBeEmpty: 'Authors prefix cannot be empty.',
        authorsPrefixCannotEqualTagsPrefix: 'Authors prefix cannot be the same as tags prefix.',
        backupLocation: 'Backup location',
        backupLocationChangedConfirmMsg: 'The backups storage location has been changed. All new backups will be stored in this directory. If you require access to earlier backups, they may be moved manually to the new directory.',
        badge: 'Badge',
        badgeAndCustomLink: 'Badge + custom link',
        badgeLabel: 'Badge label',
        basicSettings: 'Basic settings',
        byIDAscending: 'By ID ascending',
        byIDDescending: 'By ID descending',
        cannotAddIndexHTMLInURLsInfo: 'Enable this option if you cannot enable loading index.html files by default when catalog on your server is opened.',
        cardTypes: 'Card types:',
        closePostEditorOnSave: 'Close post editor on save',
        codeEditor: 'Code editor (CodeMirror)',
        colorTheme: 'Color theme',
        content: 'Content',
        cookieGroups: 'Cookie Groups',
        cookiePopup: 'Cookie Popup',
        createXMLSitemap: 'Create XML Sitemap',
        currentTheme: 'Current theme:',
        customFeedTitle: 'Custom feed title',
        customLanguageCode: 'Custom language code:',
        darkMode: 'Dark mode',
        defaultAuthorsOrdering: 'Default authors ordering:',
        defaultPostsOrdering: 'Default posts ordering:',
        defaultTagsOrdering: 'Default tags ordering:',
        descending: 'Descending',
        disableAuthorsPagination: 'Disable authors pagination',
        disableAuthorsPaginationIndexing: 'Disable authors pagination indexing',
        disableAuthorsPaginationIndexingInfo: 'If this option is enabled your authors pagination files will be excluded from the sitemap and will get <strong>noindex, follow</strong> robots metatag.',
        disableAuthorsPaginationInfo: 'If this option is enabled your authors pagination won\'t be generated.',
        disableHomepagePaginationIndexing: 'Disable homepage pagination indexing',
        disableTagsPagination: 'Disable tags pagination',
        disableTagsPaginationIndexing: 'Disable tags pagination indexing',
        disableTagsPaginationIndexingInfo: 'If this option is enabled your tags pagination files will be excluded from the sitemap and will get <strong>noindex, follow</strong> robots metatag.',
        disableTagsPaginationInfo: 'If this option is enabled your tags pagination won\'t be generated.',
        displayEmptyAuthors: 'Display authors w/o posts',
        displayEmptyAuthorsInfo: 'If this option is enabled authors without posts assigned to them will still have their subpages created and appear on the authors list.',
        displayEmptyTags: 'Display tags w/o posts',
        displayEmptyTagsInfo: 'If this option is enabled tags without posts assigned to them will still have their subpages created and appear on the tags list.',
        dontIndexThisPage: 'Ask the search engine not to crawl the whole website.',
        editors: 'Editors',
        editorWYSIWYGInfo: 'If the WYSIWYG editor strips out some tags from your HTML code, here you can add additional allowed elements.<br> For example: <strong>v-select[*],v-dropdown[*]</strong> will allow custom v-select and v-dropdown tags with any attributes.',
        enableAMP: 'Enable AMP',
        enableAMPInfo: 'AMP (accelerated mobile pages) creates mobile-optimized pages for your static content that render fast. <br/><strong>Please note:</strong> when this option is enabled your website will load third-party scripts provided by Google\'s AMP CDN.',
        enableAutoIndent: 'Enable auto-indent',
        enableCSSCompression: 'Enable CSS compression',
        enableHTMLCompression: 'Enable HTML compression',
        enableJSONFeed: 'Enable JSON feed',
        enableMediaLazyLoad: 'Enable media lazy load',
        enableMediaLazyLoadInfo: 'Enable this option if you want to use native lazy loading that lazy loads images, videos and iframes.',
        enableResponsiveImages: 'Enable responsive images',
        enableResponsiveImagesInfo: 'Enable this option if you want to deliver different sized images at different screen resolutions depending on breakpoints defined through config.json file in a theme\'s folder.',
        enableRSSFeed: 'Enable RSS feed',
        enableSharingButtons: 'Enable sharing buttons',
        enableSpellchecker: 'Enable spellchecker',
        errorPage: 'Error page:',
        errorPageFilenameCannotBeEmpty: 'Error page filename cannot be empty.',
        errorPageFilenameCannotEqualSearchPageFilename: 'Error page filename cannot be the same as search page filename.,',
        errorPageTitleVariables: 'The following variables can be used in the Error Page Title: %sitename',
        excludedFiles: 'Excluded files',
        excludeFeaturedPosts: 'Exclude featured posts',
        excludeFilesFromSitemapInfo: 'Type a comma-separated list of HTML files or catalogs to exclude from the sitemap.<br>For example: <strong>avoid-this-file.html,avoid-this-catalog-too</strong>',
        externalImages: 'External images',
        externalPage: 'External page',
        facebook: 'Facebook',
        facebookAppID: 'Facebook App ID',
        facebookAppIDInfo: 'Read how to obtain <a href="https://developers.facebook.com/docs/apps/" target="_blank" rel="noopener noreferrer">Facebook App ID</a>',
        fallbackImage: 'Fallback image',
        fallbackLogoImage: 'Fallback logo image',
        fallbackLogoImageInfo: 'The logo must fit in a 60 &times; 600 pixel box.',
        featuredPostsOrderBy: 'Featured posts order by:',
        featuredPostsOrdering: 'Featured posts ordering:',
        feedTitle: 'Feed title:',
        fefaultOrderingOnLists: 'Default ordering on lists',
        filesLocation: 'Files location',
        footerText: 'Footer text',
        frontpage: 'Frontpage',
        GDPR: 'GDPR',
        gdprBehaviourInfo: 'Remember to place a link with the above anchor in your website navigation or the website content (e.g. &lt;a href="#cookie-settings"&gt;Cookie preferences&lt;/a&gt;). Otherwise, your website\'s users might not be able to change their individual cookie preferences.',
        gdprTitle: 'Title',
        generateOpenGraphTags: 'Generate Open Graph tags',
        generateTwitterCards: 'Generate Twitter cards',
        googleAnalyticsTrackingID: 'Google Analytics Tracking ID',
        hiddenPostsOrderBy: 'Hidden posts order by:',
        hiddenPostsOrdering: 'Hidden posts ordering:',
        hideCustomExcerptsOnPostPages: 'Hide custom excerpts on post pages',
        hideCustomExcerptsOnPostPagesInfo: 'If this option is enabled your post pages won\'t display text which is placed above \"Read more\" element in the post editor.',
        homepageNoIndexPagination: 'If this option is enabled your homepage pagination files will be excluded from the sitemap and will get <strong>noindex, follow</strong> robots metatag.',
        homepagePagination: 'Homepage pagination',
        howToPrepareYourThemeForGDPRInfo: 'Enabling the GDPR Cookie Popup requires some additional changes in your theme, especially if you are using third-party scripts. <a href="https://getpublii.com/dev/prepare-theme-gdpr-compliant/" target="_blank" rel="noopener noreferrer">Read how to prepare your theme for GDPR</a>',
        imageResizeEngineInfo: 'The Sharp resize engine is much faster than Jimp, but can cause issues with some images. If you are encountering problems when creating or regenerating thumbnails, please try switching to the Jimp resize engine. Should you wish to use WebP images, then you’ll need to use the Sharp resize engine. Please note that the Sharp resize engine is unavailable on Linux.',
        imagesResizeEngine: 'Images resize engine:',
        indentSize: 'Indent size (spaces)',
        internalPage: 'Internal page',
        language: 'Language:',
        leaveBlankForDefaultBackupsDir: 'Leave blank to use default backups directory',
        leaveBlankForDefaultPreviewDirectory: 'Leave blank to use default preview directory',
        leaveBlankToUseDefaultPageTitle: 'Leave blank to use a default Page title',
        leaveBlankToUseDefaultSitesDir: 'Leave blank to use default sites directory',
        lightMode: 'Light mode',
        linkedIn: 'LinkedIn',
        linkLabel: 'Link label',
        loadAtStart: 'Load at start:',
        metaDescription: 'Meta Description:',
        metaRobots: 'Meta Robots:',
        noIndexWebsite: 'Noindex website',
        notSelected: 'Not selected',
        numberOfPostsInFeed: 'Number of posts in feed',
        openDevtoolsInMainW: 'Open DevTools automatically in the Main Window',
        openGraph: 'Open Graph',
        openLastUsedWebsite: 'Open the last used website',
        openPopupWindowBy: 'Open Popup window by',
        ordering: {
            authorASC: 'By author (ascending)',
            authorDESC: 'By author (descending)',
            createdASC: 'By created date (ascending)',
            createdDESC: 'By created date (descending)',
            idASC: 'By ID (ascending)',
            idDESC: 'By ID (descending)',
            modifiedASC: 'By modified date (ascending)',
            modifiedDESC: 'By modified date (descending)',
            nameASC: 'By name (ascending)',
            nameDESC: 'By name (descending)',
            postsCounterASC: 'By posts count (ascending)',
            postsCounterDESC: 'By posts count (descending)',
            titleASC: 'By title (ascending)',
            titleDESC: 'By title (descending)'
        },
        pageName: 'Page name',
        pageTitle: 'Page Title:',
        pageTitleVariables: 'The following variables can be used in the Page Title: %posttitle, %sitename, %authorname',
        paginationPhrase: 'Pagination phrase:',
        paginationPhraseCannotBeEmpty: 'Pagination phrase cannot be empty.',
        paginationPhraseInfo: 'Defines the phrase used before the page number in a URL e.g. <strong>https://example.com/tags/tag-slug/page/2</strong>.<br>',
        password: {
            hidePassword: 'Hide password',
            showPassword: 'Show password'
        },
        pinterest: 'Pinterest',
        postCreationDate: 'Post creation date',
        postID: 'Post ID',
        postModificationDate: 'Post modification date',
        postPageTitleVariables: 'The following variables can be used in the Post Page Title: %posttitle, %sitename, %authorname',
        postsListing: 'Posts Listing',
        postsOrderBy: 'Posts order by:',
        postsOrdering: 'Posts ordering:',
        postTile: 'Post title',
        previewLocation: 'Preview location',
        previewLocationChangedConfirmMsg: 'The preview storage location has been changed. Note that existing files in this folder will be deleted when a preview of your website is created.',
        privacyPolicyPage: 'Privacy policy page',
        privacyPolicyPageURL: 'Privacy policy page URL',
        privacyPolicyURL: 'Privacy policy URL',
        provideFacebookAppID: 'Please provide <a href="https://developers.facebook.com/docs/apps/" target="_blank" rel="noopener noreferrer">Facebook App ID</a>',
        random: 'Random',
        relatedPostsOptions: 'Related posts options',
        relatedPostsOptionsInfo: 'When enabled, related posts will be taken from all tags. When disabled, related posts will only be generated from the same tags as the current post.',
        relatedPostsOrdering: 'Related posts ordering:',
        relatedPostsSelectionMechanism: 'Related posts selection mechanism:',
        removeHTMLComments: 'Remove HTML comments',
        responsiveImagesQuality: 'Responsive Images quality',
        RSSJSONFeed: 'RSS/JSON Feed',
        saveButtonLabel: 'Save button label',
        saveSearchStateInfo: 'When enabled, Publii will save the current search results even when creating a new post, allowing you to return to the listing. By default, Publii only saves search results when opening a post to edit.',
        saveSettings: 'Save Settings',
        searchPage: 'Search page:',
        searchPageFilenameCannotBeEmpty: 'Search page filename cannot be empty.',
        searchPageTitleVariables: 'The following variables can be used in the Search Page Title: %sitename',
        selectedDirInvalid: 'Selected directory does not exist.',
        selectPage: 'Select page',
        showFeaturedImage: 'Show Featured image',
        showFeaturedImageInfo: 'Display a post\'s featured image in the feed',
        showFullText: 'Show full text',
        showFullTextInFeedInfo: 'Display full text of the post in the feed',
        showModificationDateAsColumn: 'Show modification date as column',
        showOnlyFeaturedPosts: 'Show only featured posts',
        showPostSlugsOnTheListing: 'Show post slugs on the listing',
        sitemap: 'Sitemap',
        sitemapLinkInfo: 'You can find the XML sitemap here: <a :href="sitemapLink" class="sitemap-external-link" target="_blank" rel="noopener noreferrer">sitemap.xml</a>',
        siteSettings: 'Site settings',
        siteSettingsSaveDuplicateNameErrorMessage: 'Provided site name is in use. Please try other site name.',
        siteSettingsSaveEmptyNameErrorMessage: 'Site name cannot be empty. Please try other name.',
        siteSettingsSaveNoKeyringErrorMessage: 'Publii cannot save settings due to a problem with the safe password storage software. Restart the application and try again. If the problem persists, please report it to our team via the community forum.',
        siteSettingsSaveNoKeyringErrorMessageLinux: 'Publii cannot save settings as no safe password storage software is installed. Follow the installation instructions for Node Keytar via https://github.com/atom/node-keytar/ and try again. Most likely the libsecret-1-dev and gnome-keyring packages are missing from your system.',
        siteSettingsSaveSiteNotExistsErrorMessage: 'Site does not exists. Please restart the application.',
        siteSettingsSaveSuccessMessage: 'Site settings have been successfully saved.',
        sitesLocation: 'Sites location',
        sitesLocationChangedConfirmMsg: 'The sites location has been changed. The new destination folder will be cleared up before moving there your sites files. Do you want to continue?',
        spellcheckerDoesNotSupportLanguage: 'The spellchecker does not support your selected website language. We recommend to disable this feature.',
        system: 'System',
        systemColors: 'Use system colors',
        tagPages: 'Tag pages',
        tagPageTitleVariables: 'The following variables can be used in the Tag Page Title: %tagname, %sitename',
        tagPrefix: 'Tag prefix:',
        tagPrefixInfo: 'Prefixes entered here will be added before the tag slug in the URL e.g. <strong>https://example.com/TAG_PREFIX/tag-slug</strong>.<br>This prefix is also used to generate tags list page (if supported in your theme) as <strong>https://example.com/TAG_PREFIX/index.html</strong>',
        tagsListPage: 'Tags list page',
        tagsListPageTitleVariables: 'The following variables can be used in the Tags List Page Title: %sitename',
        tagsPrefixCannotBeEmpty: 'Tags prefix cannot be empty if pretty URLs are enabled.',
        themeDoesNotHaveSupportedFeaturesList: '<p>Your theme <strong>config.json</strong> file does not contain <strong>supportedFeatures</strong> section. Please update or modify your theme to get accurate message about features which are not supported by your currently used theme. <a href="https://getpublii.com/dev/theme-supported-features" target="_blank" rel="noopener noreferrer">Read more about supported features</a>.</p>',
        themeDoesNotSupport404ErrorPage: 'Your theme does not support 404 Error page.',
        themeDoesNotSupportErrorPages: 'Your theme does not support error pages',
        themeDoesNotSupportSearchPage: 'Your theme does not support Search page.',
        themeDoesNotSupportSearchPages: 'Your theme does not support search pages',
        themeDoesNotSupportTagsListPage: 'Your theme does not support Tags list page.',
        themePrimaryColor: 'Theme primary color',
        timeFormat: 'Time format:',
        toViewSitemapEnableIndexingInfo: 'To view sitemap settings please disable the \'Ask search engines to not index this website\' option in the SEO Settings tab; the sitemap won\'t be generated for your website otherwise.',
        tumblr: 'Tumblr',
        twitter: 'Twitter',
        twitterCards: 'Twitter Cards',
        twitterUsername: 'Twitter username',
        twitteSummaryCard: 'Summary card',
        twitteSummaryCardLargeImage: 'Summary card with large image',
        urls: 'URLs',
        useAsTitlePageTitle: 'Use as a title page title',
        useAsTitlePageTitleInfo: 'When this option is enabled, og:title and twitter:title metatags will contain the page title instead of the post title, tag name or author name.',
        useGlobalConfiguration: 'Use global configuration',
        useOnlyTags: 'Use only tags',
        useOnlyTitles: 'Use only titles',
        usePrettyURLs: 'Use pretty URLs',
        usePrettyURLsInfo: 'If this option is enabled your post URLs won\'t contain the .html suffix e.g. it will change URLs from <strong>https://example.com/post.html</strong> to <strong>https://example.com/post/</strong>.',
        useSiteGlobalSettings: 'Use site global settings',
        useTitlesAndTags: 'Use titles and tags',
        usewideScrollbars: 'Use wider scrollbars',
        versionParameter: 'Version parameter',
        versionParameterInfo: 'Add version parameter in CSS/JS URLs to skip browser cache. This option can cause that more files than usual will be required to sync during deployment',
        websiteSpeed: 'Website Speed',
        whatsApp: 'WhatsApp'
    },
    site: {
        createNewWebsite: 'Create new website',
        createWebsite: 'Create website',
        createYourFirstWebsite: 'Create your first website',
        creationInProgress: 'Creation in progress...',
        erroOcurredDuringSiteDatabaseCreationInfo: 'An error occurred during site database creation. Please check your antivirus software and try again. You can also need to remove the invalid website catalog from Publii sites directory.',
        siteName: 'Site name:',
        siteWithThisNameExists: 'Site using this name exists!',
        websiteAuthorRequired: 'author name is required and should contains letters',
        websiteName: 'Website name',
        websiteNameRequired: 'website name is required'
    },
    sync: {
        configureServer: 'Configure Server',
        duringSyncYouCantChangeFilesLocation: 'During sync process you cannot change files location.',
        goToAppSettings: 'Go to app settings',
        goToSettings: 'Go to settings',
        lastRendered: 'Last rendered',
        lastSync: 'Last sync',
        preparationError: 'Preparation error',
        preparedToUpload: 'Prepared to upload',
        preparingFiles: 'Preparing files',
        previewCatalogDoesNotExistInfo: 'The preview catalog does not exist. Please go to the App Settings and select the correct preview directory first.',
        previewChanges: 'Preview your changes',
        provideAccessData: 'Provide access data',
        siteIsInSync: 'Site is in sync',
        syncInProgress: 'Sync in progress',
        syncInProgressMessage: 'During sync process you cannot change site name.',
        syncYourWebsite: 'Sync your website',
        youHaventSelectedAnyThemeInfo: 'You haven\'t selected any theme. Please go to the Settings and select the theme first.'
    },
    tag: {
        addNewTag: 'Add new tag',
        addThisAsNewTag: 'Add this as new tag',
        createFirstTag: 'You don\'t have any tag, yet. Let\'s create the first one!',
        editTag: 'Edit tag',
        filterOrSearchTags: 'Filter or search tags...',
        hideTag: 'Hide tag',
        leaveBlankToUseDefaultTagPageURL: 'Leave blank to use a default tag page URL',
        mainTag: 'Main tag',
        newTagHasBeenCreated: 'New tag has been created',
        noMainTagForPostMsg: 'If the post has tags but no main tag has been set, the first tag alphabetically will be used by default.',
        noSupportFoFeaturedImagesForTags: 'Your theme does not support featured images for tags.',
        noTagsAvailable: 'No tags available',
        noTagsMatchingYourCriteria: 'There are no tags matching your criteria.',
        removeTagMessage: 'Do you really want to remove selected tags?',
        removeTagSuccessMessage: 'Selected tags have been removed',
        saveAndPreviewNotAvailableDueToNoSupportForTagPagesInTheme: 'The "Save &amp; Preview" option is not available due to lack of support for tag pages in your theme.',
        selectTag: 'Select tag',
        selectTagPage: 'Select tag page',
        tagDataParsingErrorMessage: 'An error occurred during parsing tag data for ID: ',
        tagHasBeenEdited: 'Tag has been edited',
        tagIsNotAllowed: 'This tag is not allowed',
        tagLink: 'Tag link',
        tagName: 'Tag name:',
        tagNameCannotBeEmptyErrorMessage: 'Tag name cannot be empty. Please try other name.',
        tagNameInUseErrorMessage: 'Provided tag name is in use. Please try other tag name.',
        tagNameNotAllowedErrorMessage: 'Selected tag name/slug is not allowed.',
        tagNameSimilarInUseErrorMessage: 'Provided tag name in a similar form (case insensitive) is in use. Please try other tag name.',
        tagPage: 'Tag page',
        tagsListLink: 'Tags list link',
        tagStatusChangeSuccessMessage: 'Status of the selected tags has been changed',
        tagWillNotAppearInGgeneratedTagLists: 'Tag will not appear in any generated tag list such as post or tag/s pages.',
        thisTagIsHidden: 'This tag is hidden',
        toUseThisOptionEnableIndexingTagPages: 'To use this option, first enable indexing of tag pages in SEO settings.'
    },
    theme: {
        addThemeSuccessMessage: 'Theme has been successfully added.',
        authorsPostsPerPage: 'Authors posts per page:',
        authorsPostsPerPageInfo: 'Use -1 as value if you need to display all authors posts on page.',
        changeAppTheme: 'Change application theme',
        customSettings: 'Custom settings',
        defaultPostTemplate: 'Default post template',
        defaultTemplate: 'Default template',
        deleteTheme: 'Delete theme',
        dropYourThemeHere: 'Drop your theme here',
        excerptLength: 'Excerpt length:',
        getMoreThemes: 'Get more themes',
        goToThemesManager: 'Go to the themes manager',
        installTheme: 'Install theme',
        leaveBlankToUseDefault: 'Leave it blank to use default value',
        postOptions: 'Post options',
        postOptionsInfo: 'The Post options section allows you to set global options for what extra information should be included in your posts. Changes made in this section will affect all posts on your site, but you can also override the App Settings on the Post Edit screen for each individual post if necessary.',
        postsPerPage: 'Posts per page:',
        postsPerPageInfo: 'Use -1 as value if you need to display all posts on page.',
        removeThemeMessagePT1: 'Do you really want to remove the ',
        removeThemeMessagePT2: ' theme?',
        removeThemeSuccessMessage: 'Theme has been successfully removed.',
        resetThemeSettings: 'Reset theme settings',
        saveSettingsSuccessMessage: 'Theme settings has been successfully saved.',
        selectTheme: 'Select theme',
        settingsResetMessage: 'Do you really want to reset the theme settings?',
        settingsResetSuccessMessage: 'Theme settings has been reset.',
        tagsPostsPerPage: 'Tags posts per page:',
        tagsPostsPerPageInfo: 'Use -1 as value if you need to display all tag posts on page.',
        themes: 'Themes',
        themeSettings: 'Theme Settings',
        translations: 'Translations',
        translationsInfo: 'If you need to translate theme phrases to languages other than english - please check our documentation regarding <a href="https://getpublii.com/dev/translations-api/" target="_blank" rel="noopener noreferrer">Translations API</a><br><br>',
        updateThemeSuccessMessage: 'Theme has been successfully updated.',
        uploadThemeErrorMessage: 'The uploaded files are incorrect. Please upload theme directory or theme ZIP file.',
        websiteLogo: 'Website logo:'
    },
    ui: {
        aboutPublii: 'About Publii',
        alternativeText: 'Alternative text',
        AMP: 'AMP',
        appConfiguration: 'Application configuration',
        applyChanges: 'Apply changes',
        authors: 'Authors',
        backToTools: 'Back to tools',
        basicInformation: 'Basic information',
        cancel: 'Cancel',
        cancelPostWarningMsg: 'You will lose all unsaved changes - do you want to continue?',
        canonicalURL: 'Canonical URL',
        caption: 'Caption',
        checkDocumentation: 'Check Publii documentation',
        credits: 'Credits',
        customLink: 'Custom link',
        customTemplate: 'Custom template',
        delete: 'Delete',
        description: 'Description',
        donate: 'Donate',
        edit: 'Edit',
        featuredImage: 'Featured image',
        file: 'File:',
        fileFromFileManager: 'File from File Manager',
        frontpageLink: 'Frontpage link',
        githubRepository: 'Github repository',
        goBack: 'Go back',
        help: 'Help',
        hide: 'Hide',
        id: 'ID',
        ifCanonicalURLIsSetMmetaRobotsTagiInored: 'If canonical URL is set, the meta robots tag is ignored.',
        indexFollow: 'index, follow',
        indexNofollow: 'index, nofollow',
        iUnderstand: 'OK, I understand',
        lastModified: 'Last modified',
        leaveBlankToUseDefaultPageTitle: 'Leave it blank to use a default page title',
        linkTarget: 'Link target',
        loading: 'Loading...',
        menus: 'Menus',
        metaDescription: 'Meta description',
        metaRobotsIndex: 'Meta robots index',
        more: 'More',
        moreInformationOnPublii: 'More informations about Publii',
        moreItems: 'More items',
        name: 'Name',
        newWindow: 'New window',
        noindexFollow: 'noindex, follow',
        noindexNofollow: 'noindex, nofollow',
        none: 'None',
        notAvailableInYourTheme: 'Not available in your theme',
        notSet: 'Not set',
        ok: 'OK',
        otherOptions: 'Other options',
        pageTitle: 'Page Title',
        pleaseFillAllRequiredFields: 'Please fill all required fields',
        posts: 'Posts',
        preview: 'Preview',
        publiiOnGithub: 'View Publii on Github',
        publishAndClose: 'Publish and close',
        publishPost: 'Publish post',
        renderFrontPageOnly: 'Render front page only',
        renderFullWebsite: 'Render full website',
        reportBugInSupportdesk: 'Report a bug in our supportdesk',
        reportIssue: 'Report an issue',
        sameWindow: 'The same window',
        save: 'Save',
        saveAndClose: 'Save and close',
        saveAndPreview: 'Save & Preview',
        saveAsDraft: 'Save as draft',
        saveChanges: 'Save Changes',
        selectFile: 'Select file',
        seo: 'SEO',
        server: 'Server',
        show: 'Show',
        slug: 'Slug',
        supportPublii: 'Support Publii and donate today!',
        tags: 'Tags',
        theme: 'Theme',
        tools: 'Tools',
        unhide: 'Unhide',
        uploadInProgress: 'Upload in progress...'
    }
};
