export default {
    author: {
        addNewAuthor: 'Add new author',
        authorDataParsingErrorMessage: 'An error occurred during parsing author data for ID: ',
        authorHasBeenUpdated: 'Author has been updated',
        authorNameCannotBeEmptyErrorMessage: 'Author name cannot be empty. Please try other name.',
        authorNameInUseErrorMessage: 'Provided author name is in use. Please try other author name.',
        authorNameSimilarInUseErrorMessage: 'Provided author name in a similar form (case insensitive) is in use. Please try other author name.',
        authorSlugCannotBeEmpty: 'Author slug cannot be empty',
        avatar: 'Avatar',
        avatarAndFeaturedImage: 'Avatar and Featured image',
        cannotRemoveMainAuthor: 'You cannot remove the main author.',
        editAuthor: 'Edit author',
        eMail: 'E-mail',
        filterOrSearchAuthors: 'Filter or search authors...',
        gravatarEmailWarningMessage: 'Enter the email address you used for registering your account on Gravatar.',
        mainAuthor: 'Main author',
        mainAuthorCannotBeRemoved: 'This is a main author of this website. It cannot be removed.',
        newAuthorHasBeenCreated: 'New author has been created',
        noAuthorsMatchingYourCriteria: 'There are no authors matching your criteria.',
        removeAuthorsMessage: 'Do you really want to remove selected authors?',
        removeAuthorsSuccessMessage: 'Selected authors have been removed',
        saveAndPreviewNotAvailableDueToNoSupportForAuthorPagesInTheme: 'The "Save &amp; Preview" option is not available due to lack of support for author pages in your theme.',
        themeDoesNotSupportFeaturedImagesForAuthors: 'Your theme does not support featured images for authors',
        toUseThisOptionEnableIndexingAuthorPages: 'To use this option, first enable indexing of author pages in SEO settings.',
        useGravatarMessage: 'Use <a href="https://gravatar.com/" target="_blank" rel="noopener noreferrer">Gravatar </a> to provide your author avatar',
        useGravatarServiceMessage: 'In order to use Gravatar service provide the author e-mail at first.',
        website: 'Website'
    },
    post: {
        addNewPost: 'Add new post',
        all: 'All',
        author: 'Author',
        drafts: 'Drafts',
        duplicate: 'Duplicate',
        duplicatePostErrorMessage: 'An error occured during duplicating of selected posts. Please try again.',
        duplicatePostSuccessMessage: 'Selected posts have been duplicated',
        editorBlock: 'Block editor',
        editorBlockInfo: 'A modern and intuitive editor with shortkey and markdown support to make blogging easy, with no need to worry about HTML or other code elements.',
        editorBlockNotSupportedEditPostInfo: 'The current theme does not support the block editor used in this post. This post can be not properly rendered on the output files.',
        editorBlockNotSupportedNewPostInfo: 'The current theme does not support the block editor you want to use. This post can be not properly rendered on the output files.',
        editorBlockUse: 'Use Block editor',
        editorMarkdown: 'Markdown editor',
        editorMarkdownInfo: 'This editor supports Markdown syntax as shorthand for producing content quickly; great for extensive, no-frills projects such as documentation.',
        editorMarkdownUse: 'Use Markdown editor',
        editorWYSIWYG: 'WYSIWYG editor',
        editorWYSIWYGInfo: 'This editor provides a familiar word-processing experience, with additional tools for users that want to control every aspect of their page content.',
        editorWYSIWYGUse: 'Use WYSIWYG editor',
        editPostAnyway: 'Edit post anyway',
        excluded: 'Excluded',
        excludeFromHomepage: 'Exclude from homepage',
        featured: 'Featured',
        filterOrSearchPosts: 'Filter or search posts...',
        hidden: 'Hidden',
        hidePost: 'Hide Post',
        includeInHomepage: 'Include in homepage',
        markAsDraft: 'Mark as draft',
        markAsFeatured: 'Mark as featured',
        markAsUnfeatured: 'Mark as unfeatured',
        modificationDate: 'Modification date',
        moveToTrash: 'Move to trash',
        noPostsMatchingYourCriteria: 'There are no posts matching your criteria.',
        openEditorAnyway: 'Open editor anyway',
        postStatusChangeSuccessMessage: 'Status of the selected posts has been changed',
        publicationDate: 'Publication date',
        publish: 'Publish',
        published: 'Published',
        removePostMessage: 'Do you really want to remove selected posts? It cannot be undone.',
        removePostSuccessMessage: 'Selected posts have been removed',
        thisPostIsADraft: 'This post is a draft',
        thisPostIsExcludedFromHomepage: 'This post is excluded from homepage',
        thisPostIsFeatured: 'This post is featured',
        thisPostIsHidden: 'This post is hidden',
        title: 'Title',
        trashed: 'Trashed',
        url: 'URL'
    },
    site: {
        createNewWebsite: 'Create new website',
        createWebsite: 'Create website',
        createYourFirstWebsite: 'Create your first website',
        creationInProgress: 'Creation in progress...',
        erroOcurredDuringSiteDatabaseCreationInfo: 'An error occurred during site database creation. Please check your antivirus software and try again. You can also need to remove the invalid website catalog from Publii sites directory.',
        siteWithThisNameExists: 'Site using this name exists!',
        websiteAuthor: 'Author name',
        websiteAuthorRequired: 'author name is required and should contains letters',
        websiteName: 'Website name',
        websiteNameRequired: 'website name is required'
    },
    sync: {
        configureServer: 'Configure Server',
        goToAppSettings: 'Go to app settings',
        goToSettings: 'Go to settings',
        lastRendered: 'Last rendered',
        lastSync: 'Last sync',
        preparationError: 'Preparation error',
        preparedToUpload: 'Prepared to upload',
        preparingFiles: 'Preparing files',
        previewCatalogDoesNotExistInfo: 'The preview catalog does not exist. Please go to the App Settings and select the correct preview directory first.',
        previewChanges: 'Preview your changes',
        provideAccessData: 'Provide access data',
        siteIsInSync: 'Site is in sync',
        syncInProgress: 'Sync in progress',
        syncYourWebsite: 'Sync your website',
        youHaventSelectedAnyThemeInfo: 'You haven\'t selected any theme. Please go to the Settings and select the theme first.'
    },
    tag: {
        addNewTag: 'Add new tag',
        createFirstTag: 'You don\'t have any tag, yet. Let\'s create the first one!',
        editTag: 'Edit tag',
        filterOrSearchTags: 'Filter or search tags...',
        hideTag: 'Hide tag',
        leaveBlankToUseDefaultTagPageURL: 'Leave blank to use a default tag page URL',
        newTagHasBeenCreated: 'New tag has been created',
        noSupportFoFeaturedImagesForTags: 'Your theme does not support featured images for tags.',
        noTagsAvailable: 'No tags available',
        noTagsMatchingYourCriteria: 'There are no tags matching your criteria.',
        removeTagMessage: 'Do you really want to remove selected tags?',
        removeTagSuccessMessage: 'Selected tags have been removed',
        saveAndPreviewNotAvailableDueToNoSupportForTagPagesInTheme: 'The "Save &amp; Preview" option is not available due to lack of support for tag pages in your theme.',
        tagDataParsingErrorMessage: 'An error occurred during parsing tag data for ID: ',
        tagHasBeenEdited: 'Tag has been edited',
        tagNameCannotBeEmptyErrorMessage: 'Tag name cannot be empty. Please try other name.',
        tagNameInUseErrorMessage: 'Provided tag name is in use. Please try other tag name.',
        tagNameNotAllowedErrorMessage: 'Selected tag name/slug is not allowed.',
        tagNameSimilarInUseErrorMessage: 'Provided tag name in a similar form (case insensitive) is in use. Please try other tag name.',
        tagStatusChangeSuccessMessage: 'Status of the selected tags has been changed',
        tagWillNotAppearInGgeneratedTagLists: 'Tag will not appear in any generated tag list such as post or tag/s pages.',
        thisTagIsHidden: 'This tag is hidden',
        toUseThisOptionEnableIndexingTagPages: 'To use this option, first enable indexing of tag pages in SEO settings.'
    },
    ui: {
        alternativeText: 'Alternative text',
        authors: 'Authors',
        basicInformation: 'Basic information',
        cancel: 'Cancel',
        canonicalURL: 'Canonical URL',
        caption: 'Caption',
        credits: 'Credits',
        customTemplate: 'Custom template',
        delete: 'Delete',
        description: 'Description',
        featuredImage: 'Featured image',
        hide: 'Hide',
        id: 'ID',
        ifCanonicalURLIsSetMmetaRobotsTagiInored: 'If canonical URL is set, the meta robots tag is ignored.',
        indexFollow: 'index, follow',
        indexNofollow: 'index, nofollow',
        lastModified: 'Last modified',
        leaveBlankToUseDefaultPageTitle: 'Leave it blank to use a default page title',
        menus: 'Menus',
        metaDescription: 'Meta Description',
        metaRobotsIndex: 'Meta robots index',
        more: 'More',
        name: 'Name',
        noindexFollow: 'noindex, follow',
        noindexNofollow: 'noindex, nofollow',
        notAvailableInYourTheme: 'Not available in your theme',
        otherOptions: 'Other options',
        pageTitle: 'Page Title',
        pleaseFillAllRequiredFields: 'Please fill all required fields',
        posts: 'Posts',
        restore: 'Restore',
        saveAndPreview: 'Save &amp; Preview',
        saveChanges: 'Save Changes',
        seo: 'SEO',
        server: 'Server',
        siteSettings: 'Site settings',
        slug: 'Slug',
        tags: 'Tags',
        theme: 'Theme',
        tools: 'Tools',
        unhide: 'Unhide',
        useSiteGlobalSettings: 'Use site global settings'
    }
};
