export default {
    author: {
        addNewAuthor: 'Dodaj nowego autora',
        authorDataParsingErrorMessage: 'Wystąpił błąd podczas parsowania danych autora dla ID: ',
        authorHasBeenUpdated: 'Autor został zaktualizoway',
        authorLink: 'Link do autora',
        authorNameCannotBeEmptyErrorMessage: 'Nazwa autora nie może być pusta. Proszę podać inną nazwę.',
        authorNameInUseErrorMessage: 'Podana nazwa autora jest już używana. Proszę podać inną nazwę.',
        authorNameSimilarInUseErrorMessage: 'Podobna nazwa autora (bez rozróżniania wielkości liter) jest już używana. Proszę podać inną nazwę.',
        authorPage: 'AStrona autora',
        authorSlugCannotBeEmpty: 'Slug autora nie może być pusty',
        avatar: 'Avatar',
        avatarAndFeaturedImage: 'Avatar i obraz wyróżniony',
        cannotRemoveMainAuthor: 'Nie możesz usunąć głównego autora.',
        editAuthor: 'Edytuj autora',
        eMail: 'E-mail',
        filterOrSearchAuthors: 'Ftruj lub wyszukaj autorów...',
        gravatarEmailWarningMessage: 'Podaj adres e-mail którego użyłeś/aś do zarejestrowania konta Gravatar.',
        mainAuthor: 'Główny autor',
        mainAuthorCannotBeRemoved: 'To jest główny autor na tej stronie. Nie można go usnąć.T',
        newAuthorHasBeenCreated: 'Nowy autor został utworzony',
        noAuthorsMatchingYourCriteria: 'Brak autorów spełniających Twoje kryteria.',
        removeAuthorsMessage: 'Na pewno chcesz usunąć wybranych autorów?',
        removeAuthorsSuccessMessage: 'Wybrani autorzy zostali usunięci',
        saveAndPreviewNotAvailableDueToNoSupportForAuthorPagesInTheme: 'Opcja "Zapis i Podgląd" nie jest dostępna z powodu braku wspracia dla stron autorów w Twoim motywie.',
        selectAuthorPage: 'Wybierz stronę autora',
        themeDoesNotSupportFeaturedImagesForAuthors: 'Twój motyw nie wspiera wyróżnionych obrazków dla autorów.',
        toUseThisOptionEnableIndexingAuthorPages: 'Aby użyć tej opcji najpierw włącz, w ustawieniach SEO, indeksowanie stron autorów.',
        useGravatarMessage: 'Użyj <a href="https://gravatar.com/" target="_blank" rel="noopener noreferrer">Gravatara </a> aby dodać avatar do autora.',
        useGravatarServiceMessage: 'Aby skorzystać z usługi Gravatar podaj adres e-mail autora.',
        website: 'Strona internetowa'
    },
    menu: {
        addMenuItem: 'Dodaj element menu',
        addNewMenu: 'Dodaj nowe menu',
        addNewMenuItem: 'Dodaj nowy element menu',
        addSubmenu: 'Dodaj podmenu',
        addSubmenuItem: 'Dodaj element podmenu',
        assignedMenu: 'Przypisane menu',
        classCSS: 'Klasa CSS',
        createNewMenu: 'Stwórz nowe menu',
        deleteThisMenuItem: 'Usuń ten element menu',
        editMenuItem: 'Edytuj element menu',
        editMenuName: 'Edytuj nazwę menu',
        editThisMenuItem: 'Edytuj ten element menu',
        externalLink: 'Zewnętrzny link',
        externalURL: 'Zewnętrzyny URL',
        hideThisMenuItem: 'Ukryj ten element menu',
        internalLink: 'Link wewnętrzny',
        items: 'Elementy',
        label: 'Etykieta',
        likedItemError: 'Podlinkowany element nie jest renderowalny (pusty tag/strona autora), nie istnieje lub został usunięty.',
        likedItemIsADraft: 'Podlinkowany element jest kopią roboczą.',
        linkRelAttribute: 'Atrybut "rel" linka',
        linkTitleAttribute: 'Atrybut "title" linka',
        menu: 'Menu',
        menuIemsRemoveMessage: 'Na pewno chcesz usunąć wybrane elementy menu?',
        menuItemIsHidden: 'Ten element menu jest ukryty',
        menuNameCannotBeEmptyCreateNewMenuErrorMessage: 'Pole z nazwą menu nie może być puste.Proszę na nowo utworzyć menu.',
        menuNameCannotBeEmptyErrorMessage: 'Pole z nazwą menu nie może być puste.Proszę wprowadzić inną nazwę menu.',
        menuNameExistsErrorMessage: 'Menu o podanej nazwie już istnieje. Proszę użyć innej nazwy.',
        menuNameHasBeenEdited: 'Nazwa menu została zmieniona',
        menuNameInUseErrorMessage: 'Ta nazwa menu już używana. Proszę zmienić nazwę menu.',
        menusRemoveMessage: 'Na pewno chcesz usunąć wybrane menun?',
        menusRemoveSuccessMessage: 'Wybrane menu zostały usunięte',
        newMenuCreated: 'Nowe menu zostało utworzone',
        noMenusAvailable: 'Brak dostępnych menu',
        noMenusCreateNewOne: 'Nie masz jeszcze żadnych menu. Stwórzmy pierwsze!',
        noMenusMessage: 'Brak elementów menu; stwórz nowe używając przycisku "Dodaj element menu" znajdującego się powyżej.',
        provideNameForNewMenu: 'Podaj nazwę dla Twojego nowego menu:',
        provideNewNameForMenu: 'Podaj nową nazwę dla wybranego menu:',
        selectItemType: 'Wybierz rodzaj elment',
        selectLinkTarget: 'Wybierz target linka',
        showThisMenuItem: 'Pokaż ten element menu',
        textSeparator: 'Separator tekstu',
        type: 'Rodzaj',
        unassigned: "Nieprzypisane"
    },
    post: {
        addNewPost: 'Dodaj nowy wpis',
        all: 'Wszystkie',
        author: 'Autor',
        drafts: 'Wersje robocze',
        duplicate: 'Duplikuj',
        duplicatePostErrorMessage: 'Wystąpił błąd podczas duplikowania wybranych wpisów. Proszę spróbować ponownie.',
        duplicatePostSuccessMessage: 'Wybrane wpisy zostały zduplikowane',
        editorBlock: 'Edytor blokowy',
        editorBlockInfo: 'Nowoczesny i intuicyjny edytor wspierający skróty klawiszowe i markdown dla ułatwienia tworzenia treści na blogu bez martwienia się o HTML lub inne elementy kodu.',
        editorBlockNotSupportedEditPostInfo: 'Aktualny motyw nie wspiera edytora blokowego użytego w tym wpisie. Ten wpis nie może być poprawnie wyrenderowany do pliku wynikowego.',
        editorBlockNotSupportedNewPostInfo: 'Aktualny motyw nie wspiera edytora blokowego, którego chcesz użyć. Ten wpis nie może być poprawnie wyrenderowany do pliku wynikowego.',
        editorBlockUse: 'Użyj edytora blokowego',
        editorMarkdown: 'Edytor Markdown',
        editorMarkdownInfo: 'Ten edytor wspiera składnię Markdown jako skrót do szybszego tworzenia treści; doskonale nadaje się do obszernych, prostych projektów, takich jak dokumentacja.',
        editorMarkdownUse: 'Użyj edytora Markdown',
        editorWYSIWYG: 'Edytor WYSIWYG',
        editorWYSIWYGInfo: 'Ten edytor oferuje znajomy sposób przetwarzania tekstu oraz dodatkowe narzędzia dla użytkowników, którzy chcą mieć pod kontrolą każdy aspekt treści swojej strony.',
        editorWYSIWYGUse: 'Użyj edytora WYSIWYG',
        editPostAnyway: 'Edytuj wpis mimo to',
        excluded: 'Wykluczony',
        excludeFromHomepage: 'Wykluczony ze strony głównej',
        featured: 'Wyróżniony',
        filterOrSearchPosts: 'Filtruj lub wyszukaj wpisy...',
        hidden: 'Ukryty',
        hidePost: 'Ukryj Post',
        includeInHomepage: 'Zawrzyj na stronie głównej',
        markAsDraft: 'Oznacz jako kopię roboczą',
        markAsFeatured: 'Oznacz jako wyróżniony',
        markAsUnfeatured: 'Oznacz jako niewyróżniony',
        modificationDate: 'Data modyfikacji',
        moveToTrash: 'Przenieś do kosza',
        noPostsMatchingYourCriteria: 'Brak postów spełniających Twoje kryteria.',
        openEditorAnyway: 'Otwórz edytor mimo to',
        postLink: 'Link do wpisu',
        postPage: 'Strona wpisu',
        postStatusChangeSuccessMessage: 'Status wybranych wpisów został zmieniony',
        publicationDate: 'Data publikacji',
        publish: 'Opublikuj',
        published: 'Opublikowane',
        removePostMessage: 'Na pewno chcesz usunąć wybrane wpisy? Tej operacji nie można cofnąć.',
        removePostSuccessMessage: 'Wybrane wpisy zostały usunięte',
        selectPostPage: 'Wybierz stronę wpisu',
        thisPostIsADraft: 'Ten wpis jest kopią roboczą',
        thisPostIsExcludedFromHomepage: 'Ten wpis jest wykluczony ze strony głównej.',
        thisPostIsFeatured: 'Ten wpis jest wyróżniony',
        thisPostIsHidden: 'Ten wpis jest ukryty',
        title: 'Tytuł',
        trashed: 'Wyrzucony do kosza',
        url: 'URL'
    },
    site: {
        createNewWebsite: 'Utwórz nową stronę',
        createWebsite: 'Utwórz stronę',
        createYourFirstWebsite: 'Utwórz swoją pierwszą stronę',
        creationInProgress: 'Trwa tworzenie...',
        erroOcurredDuringSiteDatabaseCreationInfo: 'Wystąpił błąd poczas tworzenia bazy danych dla strony. Sprawdź swój program antywirusowy i spróbuj ponownie. Możliwe, że musisz również usunąć niepoprawny katalog strony z katalogu stron Publii.',
        siteWithThisNameExists: 'Strona o podanej nazwie już istnieje!',
        websiteAuthor: 'Nazwa autora strony',
        websiteAuthorRequired: 'nazwa autora strony jest wymagana i powinna zawierać litery',
        websiteName: 'Nazwa strony',
        websiteNameRequired: 'nazwa strony jest wymagana'
    },
    sync: {
        configureServer: 'Skonfiguruj serwer',
        goToAppSettings: 'Idź do ustawień aplikacji',
        goToSettings: 'Idź do ustawień',
        lastRendered: 'Ostatnie renderowanie',
        lastSync: 'Ostatnia synchronizacja',
        preparationError: 'Błąd przygotowania',
        preparedToUpload: 'Gotowe do wysłania na serwer',
        preparingFiles: 'Przygotowywanie plików',
        previewCatalogDoesNotExistInfo: 'Katalog do podglądu nie istnieje. Wybierz katalog do podglądów strony w ustawieniach aplikacji. ',
        previewChanges: 'Zobacz swoje zmiany',
        provideAccessData: 'Podaj dane dostępu',
        siteIsInSync: 'Strona zsynchronizowana',
        syncInProgress: 'Trwa synchronizacja',
        syncYourWebsite: 'Zsynchronizuj stronę',
        youHaventSelectedAnyThemeInfo: 'Nie wybrano żadnego motywu. Najpierw wybierz motyw w ustawieniach.'
    },
    tag: {
        addNewTag: 'Dodaj nowy tag',
        createFirstTag: 'Nie masz jeszcze żadnych tagów. Utwórzmy pierwszy!',
        editTag: 'Edit tag',
        filterOrSearchTags: 'Filtruj lub wyszukaj tagi...',
        hideTag: 'Ukryj tag',
        leaveBlankToUseDefaultTagPageURL: 'Pozostaw puste aby użyć domyślnego URL dla strony taga.',
        newTagHasBeenCreated: 'Nowy tag został utworzony',
        noSupportFoFeaturedImagesForTags: 'Twój motyw nie wspiera wyróżnionych obrazków dla tagów.',
        noTagsAvailable: 'Brak dostępnych tagów',
        noTagsMatchingYourCriteria: 'Brak tagów spełniających Twoje kryteria.',
        removeTagMessage: 'Na pewno chcesz usunąć wybrane tagi?',
        removeTagSuccessMessage: 'Wybrane tagi zostały usunięte',
        saveAndPreviewNotAvailableDueToNoSupportForTagPagesInTheme: 'Opcja "Zapis i Podgląd" nie jest dostępna z powodu braku wspracia dla stron tagów w Twoim motywie.',
        selectTagPage: 'Wybierz stronę taga',
        tagDataParsingErrorMessage: 'Wystąpił błąd podczas parsowania danych taga dla ID: ',
        tagHasBeenEdited: 'Tag został przeedytowany',
        tagLink: 'Link do taga',
        tagNameCannotBeEmptyErrorMessage: 'Nazwa taga nie może być pusta. Proszę podać inną nazwę.',
        tagNameInUseErrorMessage: 'Podana nazwa taga jest już używana. Proszę podać inną nazwę.',
        tagNameNotAllowedErrorMessage: 'Podana nazwa taga/slug nie jest dozwolona.',
        tagNameSimilarInUseErrorMessage: 'Podobna nazwa taga (bez rozróżniania wielkości liter) jest już używana. Proszę podać inną nazwę.',
        tagPage: 'Strona taga',
        tagsListLink: 'Link do lity tagów',
        tagStatusChangeSuccessMessage: 'Status wybranych tagów został zmieniony',
        tagWillNotAppearInGgeneratedTagLists: 'Tag nie pojawi się na żadnej z wygenerowanych list tagów takich jak strona wpisu lub taga.',
        thisTagIsHidden: 'Ten tag jest ukryty',
        toUseThisOptionEnableIndexingTagPages: 'Aby użyć tej opcji najpierw włącz, w ustawieniach SEO, indeksowanie stron tagów.'
    },
    theme: {
        addThemeSuccessMessage: 'Motyw został dodany.',
        authorsPostsPerPage: 'Authorzy na stronie:',
        authorsPostsPerPageInfo: 'Podaj wartośc -1 jeśli chcesz wyświetlać wszystkich autorów na stronie.',
        changeAppTheme: 'Zmień motyw aplikacji',
        customSettings: 'Ustawienia własne',
        defaultPostTemplate: 'Domyślny szablon wpisu',
        defaultTemplate: 'Szablon domyślny',
        deleteTheme: 'Usuń motyw',
        dropYourThemeHere: 'Upuść tutaj swój motyw',
        excerptLength: 'Długość krótkie opisu:',
        getMoreThemes: 'Pobierz więcej motywów',
        goToThemesManager: 'Przejdż do menadżera motywów',
        installTheme: 'Zainstaluj motyw',
        leaveBlankToUseDefault: 'Pozostaw puste aby użyć wartości domyślnej',
        postOptions: 'Opcje wpisów',
        postOptionsInfo: 'Sekcja opcji wpisu pozwala na ustawienie globalnych opcji dla dodatkowych informacji zawartych we wpisach. Zmiany wrpowadzone w tej sekcji będą miały wpływ na wszystkie wpisy na Twojej stronie ale możesz również, jeśli ttego potrzebujesz, nadpisać ustawienia aplikacji, dla każdego z wpisów osobno, w widoku edycji wpisu .',
        postsPerPage: 'Wpisy na stronie:',
        postsPerPageInfo: 'Podaj wartośc -1 jeśli chcesz wyświetlać wszystkie wpisy na stronie.',
        removeThemeMessagePT1: 'Czy na pewno chcesz usunąć motyw',
        removeThemeMessagePT2: ' ?',
        removeThemeSuccessMessage: 'Motyw został usunięty.',
        resetThemeSettings: 'Resetuj ustawienia motywu',
        saveSettingsSuccessMessage: 'Ustawienia motywu zosały zapisane.',
        settingsResetMessage: 'Na pewno chcesz zresetować ustawienia motywu?',
        settingsResetSuccessMessage: 'Ustawienia motywu zostały zresetowane',
        tagsPostsPerPage: 'Tagi na stronie:',
        tagsPostsPerPageInfo: 'Podaj wartośc -1 jeśli chcesz wyświetlać wszystkie tagi na stronie.',
        themes: 'Motywy',
        themeSettings: 'Ustawienia Motywu',
        translations: 'Tłumaczenia',
        translationsInfo: 'Jeśli chcesz przetłumaczyć frazy motywu na język inny niż angielski poczytaj najpierw o <a href="https://getpublii.com/dev/translations-api/" target="_blank" rel="noopener noreferrer">API Tłumaczeń</a> w naszej dokumentacji.<br><br>',
        updateThemeSuccessMessage: 'Motyw został zaktualizowany.',
        uploadThemeErrorMessage: 'Przesłane pliki są niepoprawne. Proszę przesłać katalog motywu lub plik ZIP motywu.',
        websiteLogo: 'Logo strony:'
    },
    ui: {
        aboutPublii: 'O Publii',
        alternativeText: 'Tekst alternatywny',
        appConfiguration: 'Konfiguracja aplikacji',
        appSettings: 'Ustawienia aplikacji',
        authors: 'Autorzy',
        basicInformation: 'Informace podstawowe',
        basicSettings: 'Ustawienia podstawowe',
        cancel: 'Anuluj',
        canonicalURL: 'Kanoniczny URL',
        caption: 'Podpis',
        checkDocumentation: 'Sprawdź dokumentację Publii',
        credits: 'Uznania',
        customTemplate: 'Własny szablon',
        delete: 'Usuń',
        description: 'Opis',
        donate: 'Przekaż darowiznę',
        edit: 'Edytuj',
        featuredImage: 'Obrazek wyróżniony',
        frontpageLink: 'Link do strony startwej',
        githubRepository: 'Repozytorium Github',
        goBack: 'Wróć',
        help: 'Pomoc',
        hide: 'Ukryj',
        id: 'ID',
        ifCanonicalURLIsSetMmetaRobotsTagiInored: 'Jeśłi kanoiczny URL jest ustawiony, tagi meta robotów są ignorowane.',
        indexFollow: 'index, follow',
        indexNofollow: 'index, nofollow',
        lastModified: 'Ostatnia modyfikacja',
        leaveBlankToUseDefaultPageTitle: 'Pozostaw puste aby zastosować domyślny tytuł strony',
        linkTarget: 'Otwórz w ',
        menus: 'Menu',
        metaDescription: 'Meta Opisy',
        metaRobotsIndex: 'Index meta robotów',
        more: 'Więcej',
        moreInformationOnPublii: 'Więcej informacji o Publii',
        moreItems: 'Więcej elementów',
        name: 'Nazwa',
        newWindow: 'Nowym oknie',
        noindexFollow: 'noindex, follow',
        noindexNofollow: 'noindex, nofollow',
        notAvailableInYourTheme: 'Niedostępne w Twoim motywie',
        otherOptions: 'Inne opcje',
        pageTitle: 'Tytuł Strony',
        pleaseFillAllRequiredFields: 'Proszę wypełnić wszystkie wymagane pola',
        posts: 'Wpisy',
        publiiOnGithub: 'Zobacz Publii na Github',
        renderFrontPageOnly: 'Renderuj tylko stronę główną',
        renderFullWebsite: 'Renderuj całą stronę',
        reportBugInSupportdesk: 'Zgłoś błąd w naszym naszj pomocy technicznej',
        reportIssue: 'Zgłoś problem',
        restore: 'Przywróć',
        sameWindow: 'Tym samym oknie',
        saveAndPreview: 'Zapis i Podgląd',
        saveAndPreview: 'Zapis i Pogląd',
        saveChanges: 'Zapisz zmiany',
        saveSettings: 'Zapisz Ustawienia',
        seo: 'SEO',
        server: 'Serwer',
        show: 'Pokaż',
        siteSettings: 'Ustawienia strony',
        slug: 'Slug',
        supportPublii: 'Wspieraj Publii i przekaż darowiznę już dzisiaj!',
        tags: 'Tagi',
        theme: 'Motywy',
        tools: 'Narzędzia',
        unhide: 'Odkryj',
        useSiteGlobalSettings: 'Użyj globalnych ustawień strony'
    }
};
