export default {
    posts: {
        addNewPost: 'Dodaj nowy wpis',
        all: 'Wszystkie',
        author: 'Autor',
        drafts: 'Wersje robocze',
        duplicate: 'Duplikuj',
        duplicatePostErrorMessage: 'Wystąpił błąd podczas duplikowania wybranych wpisów. Proszę spróbować ponownie.',
        duplicatePostSuccessMessage: 'Wybrane wpisy zostały zduplikowane',
        editorBlock: 'Edytor blokowy',
        editorBlockInfo: 'Nowoczesny i intuicyjny edytor wspierający skróty klawiszowe i markdown dla ułatwienia tworzenia treści na blogu bez martwienia się o HTML lub inne elementy kodu.',
        editorBlockNotSupportedEditPostInfo: 'Aktualny motyw nie wspiera edytora blokowego użytego w tym wpisie. Ten wpis nie może być poprawnie wyrenderowany do pliku wynikowego.',
        editorBlockNotSupportedNewPostInfo: 'Aktualny motyw nie wspiera edytora blokowego, którego chcesz użyć. Ten wpis nie może być poprawnie wyrenderowany do pliku wynikowego.',
        editorBlockUse: 'Użyj edytora blokowego',
        editorMarkdown: 'Edytor Markdown',
        editorMarkdownInfo: 'Ten edytor wspiera składnię Markdown jako skrót do szybszego tworzenia treści; doskonale nadaje się do obszernych, prostych projektów, takich jak dokumentacja.',
        editorMarkdownUse: 'Użyj edytora Markdown',
        editorWYSIWYG: 'Edytor WYSIWYG',
        editorWYSIWYGInfo: 'Ten edytor oferuje znajomy sposób przetwarzania tekstu oraz dodatkowe narzędzia dla użytkowników, którzy chcą mieć pod kontrolą każdy aspekt treści swojej strony.',
        editorWYSIWYGUse: 'Użyj edytora WYSIWYG',
        editPostAnyway: 'Edytuj wpis mimo to',
        excluded: 'Wykluczony',
        excludeFromHomepage: 'Wykluczony ze strony głównej',
        featured: 'Wyróżniony',
        filterOrSearchPosts: 'Filtruj lub wyszukaj wpisy...',
        hidden: 'Ukryty',
        includeInHomepage: 'Zawrzyj na stronie głównej',
        markAsDraft: 'Oznacz jako kopię roboczą',
        markAsFeatured: 'Oznacz jako wyróżniony',
        markAsUnfeatured: 'Oznacz jako niewyróżniony',
        modificationDate: 'Data modyfikacji',
        moveToTrash: 'Przenieś do kosza',
        noPostsMatchingYourCriteria: 'Brak postów spełniających Twoje kryteria.',
        openEditorAnyway: 'Otwórz edytor mimo to',
        postStatusChangeSuccessMessage: 'Status wybranych wpisów został zmieniony',
        publicationDate: 'Data publikacji',
        publish: 'Opublikuj',
        published: 'Opublikowane',
        removePostMessage: 'Na pewno chcesz usunąć wybrane wpisy? Tej operacji nie można cofnąć.',
        removePostSuccessMessage: 'Wybrane wpisy zostały usunięte',
        thisPostIsADraft: 'Ten wpis jest kopią roboczą',
        thisPostIsExcludedFromHomepage: 'Ten wpis jest wykluczony ze strony głównej.',
        thisPostIsFeatured: 'Ten wpis jest wyróżniony',
        thisPostIsHidden: 'Ten wpis jest ukryty',
        title: 'Tytuł',
        trashed: 'Wyrzucony do kosza',
        url: 'URL'
    },
    site: {
        createNewWebsite: 'Utwórz nową stronę',
        createWebsite: 'Utwórz stronę',
        createYourFirstWebsite: 'Utwórz swoją pierwszą stronę',
        creationInProgress: 'Trwa tworzenie...',
        erroOcurredDuringSiteDatabaseCreationInfo: 'Wystąpił błąd poczas tworzenia bazy danych dla strony. Sprawdź swój program antywirusowy i spróbuj ponownie. Możliwe, że musisz również usunąć niepoprawny katalog strony z katalogu stron Publii.',
        siteWithThisNameExists: 'Strona o podanej nazwie już istnieje!',
        websiteAuthor: 'Nazwa autora strony',
        websiteAuthorRequired: 'nazwa autora strony jest wymagana i powinna zawierać litery',
        websiteName: 'Nazwa strony',
        websiteNameRequired: 'nazwa strony jest wymagana'
    },
    sync: {
        configureServer: 'Skonfiguruj serwer',
        goToAppSettings: 'Idź do ustawień aplikacji',
        goToSettings: 'Idź do ustawień',
        lastRendered: 'Ostatnie renderowanie',
        lastSync: 'Ostatnia synchronizacja',
        preparationError: 'Błąd przygotowania',
        preparedToUpload: 'Gotowe do wysłania na serwer',
        preparingFiles: 'Przygotowywanie plików',
        previewCatalogDoesNotExistInfo: 'Katalog do podglądu nie istnieje. Wybierz katalog do podglądów strony w ustawieniach aplikacji. ',
        previewChanges: 'Zobacz swoje zmiany',
        provideAccessData: 'Podaj dane dostępu',
        siteIsInSync: 'Strona zsynchronizowana',
        syncInProgress: 'Trwa synchronizacja',
        syncYourWebsite: 'Zsynchronizuj stronę',
        youHaventSelectedAnyThemeInfo: 'Nie wybrano żadnego motywu. Najpierw wybierz motyw w ustawieniach.'
    },
    ui: {
        authors: 'Autorzy',
        cancel: 'Anuluj',
        delete: 'Usuń',
        hide: 'Ukryj',
        id: 'ID',
        lastModified: 'Ostatnia modyfikacja',
        menus: 'Menu',
        more: 'Więcej',
        posts: 'Wpisy',
        restore: 'Przywróć',
        server: 'Serwer',
        siteSettings: 'Ustawienia strony',
        tags: 'Tagi',
        theme: 'Motywy',
        tools: 'Narzędzia',
        unhide: 'Odkryj'
    }
};
